### ISSUE TITLE
Loading AuthComponent doesn't restrict access

### ISSUE THREAD

**Issue by commercial-hippie** [FriendsOfCake/crud#189]
As mentioned to @jippi and @lorenzo when loading both Crud and AuthComponent default methods are not restricted.

http://irc.cakephp.org/logs/link/3270191#message3270201

> Jippi: https://github.com/cakephp/cakephp/blob/3.0/src/Controller/Component/AuthComponent.php#L249-L255 CRUD injects into $controller->methods[] array, or should
> Jippi: also make sure that add() is actually in that array :)
> Jippi: line 254 should return if not, and that could be the root cause

When I don't have an `public function add(){}` in my UsersController I can access /users/add, but when I add it in the Auth denies access.

Heres some code from my AppController:

``` php
<?php
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\Event;

class AppController extends Controller {

    use \Crud\Controller\ControllerTrait;

    public $helpers = [
        'Session',
        'Form' => [
            'className' => 'Chocolate.BootstrapForm'
        ],
        'Html'
    ];

    public $components = [
        'Auth' => [
            'loginAction' => [
                'controller' => 'users',
                'action' => 'login',
            ],
            'loginRedirect' => [
                'controller' => 'users',
                'action' => 'dashboard'
            ],
            'logoutRedirect' => '/',
            'authError' => 'You either need to be logged in, or don\'t have permission to access that.',
            'authenticate' => [
                'Form' => [
                    'fields' => ['username' => 'email']
                ]
            ],
            'authorize' => ['Controller'],
            'flash' => [
                'params' => ['element' => 'flash/danger'],
                'key' => 'well'
            ]
        ],
        'Session',
        'Crud.Crud' => [
            'actions' => [
                'Crud.Index',
                'Crud.Add',
                'Crud.Edit',
                'Crud.View',
                'Crud.Delete'
            ]
        ]
    ];

    public function isAuthorized($user)
    {
        // Admin can access every action
        if (isset($user['role']) && in_array($user['role'], ['admin', 'super_admin']))
        {
            return true;
        }

        // Default deny
        return false;
    }
}
```

I don't really know much about Crud but I will have a look into this when I get playtime again. :)

**Comment by ViniciusDBarth** [comment]
I'm having this same problem, with cake 4 and  and crud 6.

**Comment by georgimavrev** [comment]
@ViniciusDBarth , to solve the problem, I added this method to my AppController.
`
    public function isAction(string $action): bool
    {
        if (!parent::isAction($action)){
            if ($this->_isActionMapped()) {
                return true;
            }
        }
        return false;
    }
`

Maybe it will be better if it was added to ControllerTrait Class like this:
`
    public function isAction(string $action): bool
    {
        if (!parent::isAction($action)){
            if ($this->_isActionMapped()) {
                return true;
            }
        }
        return false;
    }
`
