### ISSUE TITLE
CrudComponent::_handlerClassName() forces listeners to be located in a plugin 

### ISSUE THREAD

**Issue by ronnyvv** [FriendsOfCake/crud#232]
If I define a listener in AppController.php without a plugin prefix
```php
public $components = [
		'Crud.Crud' => [
			'actions' => [
				'api_index' => ['index'],
				'api_add' => ['add'],
				'api_view' => ['view'],
				'api_edit'=> ['edit'],
				'api_delete'=> ['delete']
                        ],
			'listeners' => ['ApiCms']
		],
];
```
then [CrudComponent::_handlerClassName()](https://github.com/FriendsOfCake/crud/blob/master/Controller/Component/CrudComponent.php#L714 ) forces the Crud plugin prefix - which means I have to define a plugin for my custom listener in order to use Crud via composer without having to worry about composer update removing my listener.

I realize that changing this behavior to allow listeners in app would break existing code, but perhaps it can be solved by adding a new option to CrudComponent settings to control if it should add the Crud prefix as before or trust the values as-is?

**Comment by jippi** [comment]
This is no longer the case
