### ISSUE TITLE
3.x ApiPaginationListener not responding to `direction` parameter

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud#247]
The ApiPaginationListener is responding to the direction query string parameter. E.g.

    api.local?direction=asc 

Additional info:

- I have whitelisted the action just as ``limit``, ``sort`` and ``page`` which do work as expected (all three)
- I have tested with option ``order`` as well
- using latest Cake 3.x and CRUD

Am I missing something here?

**Comment by ADmad** [comment]
Have you tried whitelisting `direction` too?

**Comment by bravo-kernel** [comment]
Yes I did and maybe not worded clearly but limit, sort and page are in the same whitelist array and function as expected.

**Comment by ADmad** [comment]
Just `api.local?direction=asc` isn't going to work, it needs field name too eg. `api.local?sort=some_field&direction=asc`

**Comment by bravo-kernel** [comment]
Damn, my bad. I somehow thought it "just" worked in 2.x. 

Thanks for clarifying, sorry for disturbing.
