### ISSUE TITLE
Scrutinizer dependency check fails on cake3 crud

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud#250]
Hi guys, I hope this is not caused by a configuration error on my side but my scrutinizer fails on (just) crud. All other dependencies work as expected (including other C3 plugins).

```
  Notice: Undefined index: cake\event\event in vendor/scrutinizer/php-analyzer/src/Scrutinizer/PhpAnalyzer/Model/Repository/EntityTypeProvider.php line 131  
```

The details can be found [here](https://scrutinizer-ci.com/g/alt3/cakephp-app-plusplus/inspections/c988a912-939b-4dd4-a0e3-6b4acf2ca2cc). Just click on the red cross.

**Comment by jadb** [comment]
Where is `cake\event\event` used without property capitalization? Looks like its related to something like that.

**Comment by bravo-kernel** [comment]
I will check my plugin for any lower casing in my plugin tomorrow. Would be akward to say the least 😏

**Comment by bravo-kernel** [comment]
Just checked and there are only two references to Cake\Event\Event in my (almost empty) plugin and they are using the **correct casing**, just like found in the CRUD plugin:

```php
use Cake\Event\Event;

    /**
     * beforeFilter
     *
     * @param Cake\Event\Event $event Event instance
     * @return void
     */
    public function beforeFilter(Event $event)
    {
        pr("AppPlusPlus component beforeFilter()");
    }
```

Could it be related to the CRUD plugin and not my code? No biggie if this isn't solved, I can just disable Scrutinizer for the time being.

**Comment by bravo-kernel** [comment]
Spotted one difference though, CRUD uses a leading \, testing right now.

```php
* @param \Cake\Event\Event $event Event instance
```

**Comment by jippi** [comment]
feel free to PR a fix for it :)

**Comment by bravo-kernel** [comment]
Sorry guys, I have triple-checked my sources and even disabled everything remotely related to this but the outcome is still the same and because the Scrutinizer information is so limited I honestly have no idea what to investigate next.

**Comment by bravo-kernel** [comment]
I have stripped my app to the bare minimum but the issue persists. Since this plugin is pretty rock-solid the issue could very well be caused by some configuration f*** up on my behalf so... feel free to close if you guys think this is one of those cases.

**Comment by dakota** [comment]
For the record, I am getting the exact same issue.

**Comment by dakota** [comment]
Asked Scrutinizer support, and they said:

> it seems like in that dependency, there is somewhere a reference to a class ``Évent`` (note the apostrophe on the first E) which is causing problems with the analyzer. We will release a fix for this shortly, but it's probably also a bug in that dependency which you might want to fix/report.

Although, can't actually find any such reference.

**Comment by bravo-kernel** [comment]
@dakota thanks for looking into this, very interesting to say the least

**Comment by dakota** [comment]
@bravo-kernel Well, it's affecting me as well :)

**Comment by ADmad** [comment]
Closing and PR has been opened.
