### ISSUE TITLE
Docs for RedirectListener

### ISSUE THREAD

**Issue by stefanozoffoli** [FriendsOfCake/crud#257]
Hi,
Crud's listeners are very useful, but the documentation page for RedirectListener is missing and I don't know how to use it. :)
http://crud.readthedocs.org/en/latest/listeners/redirect.html

Thank you all!

**Comment by adayth** [comment]
+1

**Comment by davidyell** [comment]
:+1:

**Comment by jippi** [comment]
It's complete, just not documented :)

If someone can PR the first draft from it, I can complete it

**Comment by jippi** [comment]
No-one did :(

**Comment by stefanozoffoli** [comment]
Maybe this can be a good start?

https://github.com/FriendsOfCake/crud/blob/gh-pages/docs/listeners/redirect.md

**Comment by jippi** [comment]
yes :) PR it :D
