### ISSUE TITLE
Repository Readme wrong composer install

### ISSUE THREAD

**Issue by adayth** [FriendsOfCake/crud#258]
"composer install friendsofcake/crud:~4.0" should be changed by  "composer require friendsofcake/crud:~4.0"

**Comment by ADmad** [comment]
Would you mind making a pull request fixing it?

**Comment by adayth** [comment]
No problem, tell me the right branch please.

**Comment by lorenzo** [comment]
@adayth master

**Comment by ADmad** [comment]
Fixed in #259
