### ISSUE TITLE
Stop developing 3.x series of crud

### ISSUE THREAD

**Issue by josegonzalez** [FriendsOfCake/crud#262]
Now that CakePHP 3.x is out, we should implement all 3.x Crud features in 4.x Crud. I noticed we continued to write new features and bugfixes, and while I'll all for fixing bugs, adding features for an older version without re-implementing them for the newer version won't end well.

Thoughts? I can make an initial inventory of what we'd need to re-implement for Crud 4.x and we can work from there :)

**Comment by jadb** [comment]
:+1:

**Comment by lorenzo** [comment]
sounds good to me

**Comment by davidyell** [comment]
Makes sense to me, and it'll also help with promoting the RAD aspects of the Framework to new potential users who are working on prototype system or with short timescales.

**Comment by jippi** [comment]
OK!
