### ISSUE TITLE
Jippi's bot is annoying ;)

### ISSUE THREAD

**Issue by jadb** [FriendsOfCake/crud#269]
![screen shot 2015-05-23 at 6 03 12 am](https://cloud.githubusercontent.com/assets/33527/7783462/8c49a73e-0111-11e5-99b9-59bc6b9b06fd.png)

Please! Turn that damn thing off or silence it. It started all of a sudden, and been going at it for weeks now.

**Comment by jippi** [comment]
hmm, it should only run once per day

**Comment by jadb** [comment]
Thanks!!
