### ISSUE TITLE
4.x) RelatedModelsListener unable to load belongsTo?

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#272]
Relates to #257

**What I'm trying**
```php
$this->loadComponent('RequestHandler');
$this->loadComponent('Crud.Crud', [
    'actions' => [
        'index' => [
            'className' => 'Crud.Index',
            'relatedModels' => [
                'Statuses',
//              'Statuses' => 'belongsTo'
            ]
        ],
        'view' => ['className' => 'Crud.View']
    ]
]);

$this->Crud->addListener('Crud.Api');
$this->Crud->addListener('Crud.ApiPagination');
$this->Crud->addListener('Crud.RelatedModels');
```

I'm then hitting my `/api/products.json`.

**What I'd expect to happen**
I would expect that the Statuses table related data would be joined to my returned data.

**What is happening?**
The data is returned without any additional table data joined.

**Why I think it's happening**
https://github.com/FriendsOfCake/crud/blob/master/src/Listener/RelatedModelsListener.php#L70
Because this will always equate to a boolean there is no way that any change made to the configuration passed to the component will ever impact this.

So when the `getAssociatedByType` method is called, the `belongsTo` relationship is ignored.

**Comment by ADmad** [comment]
> I would expect that the Statuses table related data would be joined to my returned data.

That's not what it's supposed to do. The `RelatedModelsListener` is for setting view vars for options lists for related models. In your case it will set `$statuses` view var with options list for `status_id` field for your products.

> So when the getAssociatedByType method is called, the belongsTo relationship is ignored.

The `manyToOne` is the belongsTo association https://github.com/cakephp/cakephp/blob/master/src/ORM/Association/BelongsTo.php#L115

**Comment by davidyell** [comment]
I'd say the class wasn't named especially descriptively then. `RelatedListDataListener` would be better I think. Ah well, I'd hoped it would save me some time.

Perhaps this can be detailed once #257 is completed.

**Comment by ADmad** [comment]
> Perhaps this can be detailed once #257 is completed.

#257 is about **RedirectLister**.  Redirect != RelatedModels.

**Comment by ADmad** [comment]
You could have read http://crud.readthedocs.org/en/latest/listeners/related-models.html instead of assuming what the listener does :)

**Comment by davidyell** [comment]
Urgh, seems I really fail at reading today.
