### ISSUE TITLE
Controller shutdown not properly working on exception (ApiListener)

### ISSUE THREAD

**Issue by sean-nicholas** [FriendsOfCake/crud#276]
*Crud/Error/ExceptionRenderer* overwrites *_outputMessage* but does not call *$this->_shutdown()* like *Cake/Error/ExceptionRenderer*: https://github.com/cakephp/cakephp/blob/master/src/Error/ExceptionRenderer.php#L297

So my DispatcherFilter to set access controll headers does not get called on normal exceptions. It only gets called if a validation exception occures because *_customMethod* in *Cake/Error/ExceptionRenderer* is invoked and it calls *$this->_shutdown()*: https://github.com/cakephp/cakephp/blob/master/src/Error/ExceptionRenderer.php#L185

My first attempt was to add *$this->_shutdown* to *_outputMessage* (77-78):

```php
$this->controller->afterFilter($event);
$this->_shutdown();
return $this->controller->response;
```

But now *$this->_shutdown()* gets called twice on validation exceptions. So I changed *_customMethod* and removed *$this->_shutdown()*. 

I dont think that is a great solution. Maybe you know a better one?

**Comment by lorenzo** [comment]
Exceptions will get you out of the normal execution flow and you should not expect your controller filters to be called in that case. What logic do you have in shutdown() ?

**Comment by sean-nicholas** [comment]
I need CORS Headers in each response. I am adding them in a DispatcherFilters afterDispatch Method. ExceptionRenderer->_shutdown() triggers this method.

**Comment by lorenzo** [comment]
What about using a dispatcher filter instead?

This is one example of how to do it: https://github.com/snelg/cakephp-cors

**Comment by ADmad** [comment]
@lorenzo He is using DispatchFilter, but `afterDispatch()` instead of `beforeDispatch()` :)

@sean-nicholas Just switch to using `beforeDispatch()` and your issue is solved.

**Comment by sean-nicholas** [comment]
@ADmad Ahh, perfect. Thank you :)

**Comment by sean-nicholas** [comment]
I am sorry. I could not get it work. I changed my DispatcherFilter from afterDispatch to beforeDispatch and also used https://github.com/snelg/cakephp-cors
Nothing worked. Every time an Exception gets raised a new Response is created: https://github.com/cakephp/cakephp/blob/master/src/Error/ExceptionRenderer.php#L107 So my old one with my CORS Headers wont be used any more. Are you sure beforeDispatch is the right place?

**Comment by bravo-kernel** [comment]
Any update on this, I am experiencing the same:

1. CORS dispatch filter using `beforeDispatch()`
2. headers definitely set in dispatchfilter
3. gone when the CRUD exception reaches my REST client

**Comment by bravo-kernel** [comment]
For future references: changing the DispatchFilter to use `afterDispatch()` totally solved this.

**Comment by ADmad** [comment]
No idea why I thought using `beforeDispatch()` would work. Since a new response instance is created by exception renderer it has to be in `afterDispatch()` :stuck_out_tongue:
