### ISSUE TITLE
Error Installing on Cake 3.0

### ISSUE THREAD

**Issue by andrewk87** [FriendsOfCake/crud#278]
I followed the book exactly to install CRUD 4.0 on cake 3.0 but keep getting the following error:
Fatal error: Trait 'Crud\Controller\ControllerTrait' not found

**Comment by jippi** [comment]
did you load the plugin ? did you add composer autoload?

**Comment by ADmad** [comment]
@jippi Btw http://crud.readthedocs.org isn't auto updating. Eg. http://crud.readthedocs.org/en/latest/installation.html  mention "dev-cake3" in composer command while it's been updated here https://github.com/FriendsOfCake/crud/blob/master/docs/installation.rst

**Comment by jippi** [comment]
@ADmad I'm seeing the following error in readthedocs:

```
html
-----


Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/crud/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/crud/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/crud/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    if not ext_meta.get('version'):
AttributeError: 'Sphinx' object has no attribute 'get'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/crud/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    if not ext_meta.get('version'):
AttributeError: 'Sphinx' object has no attribute 'get'
The full traceback has been saved in /tmp/sphinx-err-rAkFLq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks
!```

No idea what that mean, other than a possible version mismatch or something like that

**Comment by ADmad** [comment]
I have no idea either :(

@antograssiot Would have to have any idea? :smile:

**Comment by jippi** [comment]
I think I got it working, disabling some random highlightning thing.. has to be a version mis-match somewhere introduced by read the docs

**Comment by andrewk87** [comment]
I loaded the plugin but not using composer. Downloaded crud 4.0 from gitlab
then placed it in /plugins/Crude loaded the plugin in the bootstrap finally
added the uses in the app controller but keep getting the error. I have
always loaded the plugins the same way since cake 1.2 never had an issue.

Is composer required now?

**Comment by jadb** [comment]
How are you loading the plugin in `config/bootstrap.php`?

I only use it with composer but I think it should work without if you tell CakePHP to autoload the plugin classes:

```
Cake\Core\Plugin::load('Crud', ['autoload' => true]);
```

**Comment by andrewk87** [comment]
I was using loading the plugin using:

Plugin::load('Crud');

As per the installation docs. Using:

Plugin::load('Crud', ['autoload' => true]);

looks to have resolved the issue. Thanks for the help!

**Comment by ADmad** [comment]
> As per the installation docs.

The installation docs also tell you to use composer to get the plugin, which you didn't :)

**Comment by andrewk87** [comment]
Lol true. I will read more carefully next time.
Maybe a bit in the docs for those that don't use composer will be helpful
for those in the future.
Thanks again for the help, and for the great work on CRUD dev love the
plugin. Use it in all my cake apps.

**Comment by orbitTVO** [comment]
Not trying to be a necromancer, but I used **composer require friendsofcake/crud** and still I suffered from this issue.

To resolve it, I had to follow the same steps as akeiper explained in his second-to-last repsonse, to add autoload=true to the plugin-load step in bootstrap.php.

**Comment by dakota** [comment]
@orbitTVO What version of CakePHP, and what was the outcome of the composer require?

**Comment by orbitTVO** [comment]
This was the outcome of composer require, luckily the Windows Command Prompt window was still open:
`Letter:\path>composer require friendsofcake/crud
Using version ^4.4 for friendsofcake/crud
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing friendsofcake/crud (4.4.2) Downloading: 100%
friendsofcake/crud suggests installing friendsofcake/search (Provides search capabilities for the Crud plugin.)
friendsofcake/crud suggests installing friendsofcake/crud-view (Automated admin backend based on your Crud configuration.)
friendsofcake/crud suggests installing neomerx/json-api (Framework agnostic JSON API (jsonapi.org) implementation)
Writing lock file
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump
`

The version of cake is 3.3.15

**Comment by kamlesh131986** [comment]
i have got followings error. how to resolve that? All things are set like routs, api/appcontroller, api/usercontroller, /config/bootstrap in set Plugin::load('ADmad/JwtAuth'), Plugin::load('Crud');

Cake\View\Exception\MissingTemplateException

Error: The view for UsersController::add() was not found.

Confirm you have created the file: "Api\Users\add.ctp" in one of the following paths:

F:\app_cpv3\src\Template\Api\Users\add.ctp
If you want to customize this error message, create src\Template\Error\missing_template.ctp

**Comment by bravo-kernel** [comment]
@kamlesh131986 this is mostly caused by not sending the correct `Accept` and/or `Content-Type` headers. 

Also please note that this is not a help-forum, please use SO, Slack or IRC for that.
