### ISSUE TITLE
Enhancement: Adding a beforeMarshal event

### ISSUE THREAD

**Issue by chrisShick** [FriendsOfCake/crud#279]
I was wondering if there was a plan to add a beforeMarshal event to the crud add action.

**Comment by ADmad** [comment]
What's your use case?

**Comment by chrisShick** [comment]
I want to be able to save additional data when a user registers to another table. The other table is another association. So, I would pass in the additional data to the beforeMarshal event so that it can be saved through the association.

**Comment by jippi** [comment]
Sounds a lot like [https://github.com/FriendsOfCake/crud/blob/master/src/Action/AddAction.php#L119](beforeSave)

**Comment by ADmad** [comment]
@jippi The entity is already created before Crud.beforeSave is triggered. So while associated record can be added to the entity can't just set associated data array to it.

@chrisShick Can't you just use Model.beforeMashal to add associated data?

**Comment by jippi** [comment]
@ADmad I'm seeing the following error in readthedocs:

```
html
-----


Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/crud/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/crud/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/crud/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    if not ext_meta.get('version'):
AttributeError: 'Sphinx' object has no attribute 'get'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/crud/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    if not ext_meta.get('version'):
AttributeError: 'Sphinx' object has no attribute 'get'
The full traceback has been saved in /tmp/sphinx-err-rAkFLq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks
!```

No idea what that mean, other than a possible version mismatch or something like that

**Comment by chrisShick** [comment]
@jippi I was just about to say what @ADmad just said. The data is already marshaled into an entity and it won't save associated data as an array.

@ADmad The additional data that needs to be saved is unique to each user and is only available at the controller level.

**Comment by ADmad** [comment]
@chrisShick That shouldn't be an issue. Set the listener from controller using `$this->User->eventManger->on('Model.beforeMarhal', function($event) { //your magic here});`

**Comment by chrisShick** [comment]
Ahhh @ADmad I had totally forgotten about the built-in events for the models!! XD Thank you.

**Comment by chrisShick** [comment]
@ADmad after coming back to this nearly two years later, I notice the suggested solution that you provided does not work. I opened up a [bug](https://github.com/FriendsOfCake/crud/issues/507).
