### ISSUE TITLE
Invalid CSRF token on edit method

### ISSUE THREAD

**Issue by mneil** [FriendsOfCake/crud#281]
First off, awesome libraries :).

I'm using the CSRF component and everything works fine except for Edit methods.

Basic blog example:
```
 public function edit($id) {

    $this->Crud->action()->config('scaffold.fields_blacklist', ['created', 'user_id']);
    return $this->Crud->execute();
  }
```

My CRUD configuration
```
'Crud.Crud' => [
      'actions' => [
        'Crud.Index',
        'Crud.Add',
        'Crud.Edit',
        'Crud.View',
        'Crud.Delete'
      ],
      'listeners' => [
        'Crud.Api',
        'Crud.ApiQueryLog',
        'Crud.RelatedModels',
        'Crud.Redirect',
        'CrudView.View',
        'CrudView.Search',
      ]
    ]
```

I notice that no matter what my generated _csrf token is the same on all edit methods. Leads me to believe the hash that's being generated is from incorrect or empty data.

Any ideas or help on places to look?

Thanks!

**Comment by jippi** [comment]
CRUD doesn't do anything with CSRF at all :)

**Comment by mneil** [comment]
Ok thanks, that helps a little. Looks like the issue is actually in the crud-view library. I'll open a ticket in that repo and continue digging to see if I can figure out why.
