### ISSUE TITLE
Running the tests with phpunit 4.7.x

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#283]
I was updating the tests and I noticed that if you define the `modelClass` in the controller Crud will automatically try and access the table inflected from the controller, rather than the table defined in the Table class.

```php
// src/Controller/ExamplesController.php
class ExamplesController extends AppController {
    public function initialize()
    {
        $this->modelClass = 'Kittens';
    }

// src/Model/Table/KittensTable.php
class Kittens extends Table {
    public function initialize(array $config)
    {
        $this->table('kittens');
    }
}
```

Crud, by default, will try and find the `examples` table in the database, rather than reading the `modelClass`.

The [example of the setup in the tests is here](https://github.com/FriendsOfCake/crud/blob/master/tests/TestCase/Controller/Component/CrudComponentTest.php#L60),  as [this table uses the `posts` table](https://github.com/FriendsOfCake/crud/blob/master/tests/App/Model/Table/CrudExamplesTable.php#L32) but the test fails because the `crud_examples` table doesn't exist.

Be sure to run the tests with `phpunit/phpunit` `~4.7`

**Comment by ADmad** [comment]
> The example of the setup in the tests is here, as this table uses the posts table but the test fails because the crud_examples table doesn't exist.

Running the testsuite I don't get any failures.

**Comment by davidyell** [comment]
@ADmad  You don't even get a deprecated warning for the fact that `assertTag()` has been removed from phpunit?

**Comment by jippi** [comment]
travis is happy - all is good?

**Comment by davidyell** [comment]
Travis is happy with `PHPUnit 3.7.33 by Sebastian Bergmann.`

**Comment by ADmad** [comment]
Until someone finds the time to update the use of deprecated/removed methods like `assertTag()` it's gonna keep using 3.7.

**Comment by davidyell** [comment]
Yep, that was the main thing which tripped me up, and the guy replacing the assertions hasn't updated his code.
