### ISSUE TITLE
RFC: Crud bake theme

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#286]
I just had the idea that a Crud bake theme could be created. It would be very basic and essentially just have empty controller templates.

Then you could generate your controllers using bake.

Would this be quicker than using 'File > New class'? I guess that depends on your IDE.

**Comment by josegonzalez** [comment]
Go ahead and add the bake templates for the controllers :)

**Comment by davidyell** [comment]
Okay, I'll try and get a PR in some time today.

**Comment by davidyell** [comment]
Closed in favour of #297 PR
