### ISSUE TITLE
Auto-loading related Tables

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#287]
**Scenario**
I've made my admin index view and baked some views. It so happens that this table Examples, has a `status_id` field which relates to the Statuses table. This data isn't loaded.

**What I did**
In my AppController I made a method which I called from my `beforeFilter`.

```php
protected function addRelatedTables()
{
    if (!is_array($this->paginate['contain']) || !isset($this->paginate['contain'])) {
        $this->paginate['contain'] = [];
    }

    $this->Crud->on('beforePaginate', function (Event $event) {
        foreach($this->{$this->modelClass}->associations() as $table => $association) {
            $this->paginate['contain'] = array_merge(
                $this->paginate['contain'],
                [$this->{$this->modelClass}->association($table)->name()]
            );
        }
    });
}
```

**Suggestions**
Is it worth making this into a listener in a similar vein to the RelatedModelsListener?

**Concerns**
With so many ways to configure the Paginator component, my code example above relies on the shortcut pagination array, and I don't know if it would be merged accurately with someone using the paginator component directly, such as `$this->Paginator->paginate($Table, $optionsArray)`.

Also I'd be interested in thoughts on how configure such a thing in a more application wide way, to prevent controller specific configuration, which, to me, defeats the point of the Crud plugin.

**Comment by ADmad** [comment]
[ViewListener::beforePaginate()](https://github.com/FriendsOfCake/crud-view/blob/master/src/Listener/ViewListener.php#L33) of crud-view does similar. It would be nice to have that in crud itself. A separate listener isn't necessary, can be done in `RelatedModelsListener` itself.

**Comment by jippi** [comment]
Feel free to dump it into CRUD - I can see the usage for it too :)

**Comment by davidyell** [comment]
Closing in favour of #304
