### ISSUE TITLE
Nested related models

### ISSUE THREAD

**Issue by Laykou** [FriendsOfCake/crud#292]
Hi,

This was previously working and now is not:

```PHP
$contain = [
    'Comments' => ['Users'],
    'Category.Topic'
];
$this->Crud->listener('relatedModels')->relatedModels($contain, 'add');
```

It fails on https://github.com/FriendsOfCake/crud/blob/master/src/Listener/RelatedModelsListener.php#L141 as the `$associationClass` equals to `NULL`.

Thank you for the support.

**Comment by Laykou** [comment]
Oh sorry, I don't know what I was thinking ... It is a different think than doing contain in `beforeFind()`.

However the docs here is misleading, or isn't it? http://crud.readthedocs.org/en/latest/listeners/related-models.html What means the `Cm.Tags`? Is it a plugin?

**Comment by ADmad** [comment]
It only takes a flat array so pass it that.

**Comment by ADmad** [comment]
> This was previously working

I could be wrong but I don't remember it ever working with nested models.

**Comment by ADmad** [comment]
Are you sure you are not misunderstanding what this listener does? It populates view vars for foreign key select lists so how is a nested array of models going to help?

**Comment by Laykou** [comment]
Sorry, yes, nested array is a mistake. However I tried to use flat array, but it does not work for me. The same error .... it looks like the `$table->associations()->get('Comments.Users')` returns null. Could there be some recent changes in cakephp? Or is this covered by some tests?

I haven't done any further investigation yet.

**Comment by ADmad** [comment]
`Table::associations()` only returns list of direct associations. Nothing has changed recently in the core in that aspect afaik. 

Closing the ticket it doesn't seem to be directly related to this plugin.
