### ISSUE TITLE
Including crud as part of another project

### ISSUE THREAD

**Issue by pliablepixels** [FriendsOfCake/crud#299]
Hello, the installation of Crud indicates two methods:

a) via composer

b) Via git submodule add/init/update

When one adds crud via git submodule, it looks like Plugin/Crud/Lib is not created. Option b) seems to download the source. Do I need to do anything else besides git add/init/update to get the Lib directory? If that does not exist, Cake files that use Crud fail with CrudTraitController not found.

Everything works fine when installed with composer, but I need to use option b.

thanks!

**Comment by jippi** [comment]
Cake 2 or 3?

**Comment by pliablepixels** [comment]
cake 2

**Comment by pliablepixels** [comment]
Some more information:

Crud was added this way in the project I am facing a problem with
https://github.com/ZoneMinder/ZoneMinder/blob/master/.gitmodules

When I git clone the above project, then do git submodule init and git submodule add, it pulls in crud, but does not create the Lib directory

**Comment by josegonzalez** [comment]
@pliablepixels maybe you need to do:

```
git submodule init
git submodule update
```

**Comment by pliablepixels** [comment]
sorry, I mean init followed by update (not add) - doing that does not produce Lib

**Comment by jippi** [comment]
I still don't understand the issue here :) 

using Composer works just fine :)

**Comment by pliablepixels** [comment]
Hello, the issue is that the documented alternate process of installing CRUD as per http://crud.readthedocs.org/en/latest/installation.html does not seem to work

The problem is that the folks at ZoneMinder (https://github.com/ZoneMinder/ZoneMinder) have added CRUD as per the git submodule instructions. When people check out their code followed by git submodule init & update, it pulls in CRUD but without Lib

They have a policy that any 3rd party repositories should only be downloaded at build time, not at compile time, which is why the have followed the ```git submodule```  approach in your documentation, which actually does not seem to  work fully.

So I am trying to figure out a way in which I can advise them to modify their crud include instructions that also bring in the Lib directory. I hope I was able to explain the situation.

**Comment by josegonzalez** [comment]
@pliablepixels The instructiosn seem to work fine, and I was able to produce the lib directory after cloning:

```shell
jose@mactaku:~/src/test  $ git clone git@github.com:ZoneMinder/ZoneMinder.git
Cloning into 'ZoneMinder'...
remote: Counting objects: 46218, done.
remote: Compressing objects: 100% (80/80), done.
remote: Total 46218 (delta 35), reused 0 (delta 0), pack-reused 46137
Receiving objects: 100% (46218/46218), 37.61 MiB | 7.13 MiB/s, done.
Resolving deltas: 100% (33709/33709), done.
Checking connectivity... done.
jose@mactaku:~/src/test  $ cd ZoneMinder/
jose@mactaku:~/src/test/ZoneMinder git:master $ git submodule init
Submodule 'web/api/app/Plugin/Crud' (https://github.com/FriendsOfCake/crud.git) registered for path 'web/api/app/Plugin/Crud'
jose@mactaku:~/src/test/ZoneMinder git:master $ git submodule update
Cloning into 'web/api/app/Plugin/Crud'...
remote: Counting objects: 39321, done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 39321 (delta 62), reused 0 (delta 0), pack-reused 39232
Receiving objects: 100% (39321/39321), 9.35 MiB | 6.18 MiB/s, done.
Resolving deltas: 100% (28273/28273), done.
Checking connectivity... done.
Submodule path 'web/api/app/Plugin/Crud': checked out 'e22c1563a51d86aac0d5054beee28b4afb60c802'
jose@mactaku:~/src/test/ZoneMinder git:master $ ll web/api/app/Plugin/Crud
total 64
drwxr-xr-x  17 jose  staff   578B Jul 15 12:17 .
drwxr-xr-x   4 jose  staff   136B Jul 15 12:17 ..
-rw-r--r--   1 jose  staff   318B Jul 15 12:17 .editorconfig
-rw-r--r--   1 jose  staff    60B Jul 15 12:17 .git
-rw-r--r--   1 jose  staff    48B Jul 15 12:17 .semver
-rw-r--r--   1 jose  staff   628B Jul 15 12:17 .travis.yml
-rw-r--r--   1 jose  staff   2.9K Jul 15 12:17 CONTRIBUTING.md
drwxr-xr-x   3 jose  staff   102B Jul 15 12:17 Console
drwxr-xr-x   4 jose  staff   136B Jul 15 12:17 Controller
drwxr-xr-x   4 jose  staff   136B Jul 15 12:17 Error
-rw-r--r--   1 jose  staff   1.1K Jul 15 12:17 LICENSE.txt
drwxr-xr-x   4 jose  staff   136B Jul 15 12:17 Lib
-rw-r--r--   1 jose  staff   3.1K Jul 15 12:17 README.md
drwxr-xr-x   3 jose  staff   102B Jul 15 12:17 Routing
drwxr-xr-x   5 jose  staff   170B Jul 15 12:17 Test
drwxr-xr-x   5 jose  staff   170B Jul 15 12:17 View
-rw-r--r--   1 jose  staff   1.3K Jul 15 12:17 composer.json
jose@mactaku:~/src/test/ZoneMinder git:master $ ls -lah web/api/app/Plugin/Crud/Lib
total 8
drwxr-xr-x   4 jose  staff   136B Jul 15 12:17 .
drwxr-xr-x  17 jose  staff   578B Jul 15 12:17 ..
-rw-r--r--   1 jose  staff   1.7K Jul 15 12:17 CrudControllerTrait.php
drwxr-xr-x   3 jose  staff   102B Jul 15 12:17 Panel
jose@mactaku:~/src/test/ZoneMinder git:master $
```

**Comment by pliablepixels** [comment]
@josegonzalez - you are right!  Today it is indeed pulling Lib.
Till yesterday it was pulling src.

I have no idea why -- the ZM folks did not change anything.

Closing. Thanks.
