### ISSUE TITLE
CrudExamplesTable::_findUnpublished does not return the modified $query

### ISSUE THREAD

**Issue by michelpeters** [FriendsOfCake/crud#305]
CrudExamplesTable::_findUnpublished does not return the modified $query, but _findPublished does.

See: https://github.com/FriendsOfCake/crud/blob/master/tests/App/Model/Table/CrudExamplesTable.php#L57

Code from _findUnpublished:
```php
 protected function _findUnpublished(Query $query, array $options)
    {
        $query->where(['published' => 'N']);
    }
```

to:
```php
 protected function _findUnpublished(Query $query, array $options)
    {
        $query->where(['published' => 'N']);
        return $query;
    }
```

----
I've created a PR for this: https://github.com/FriendsOfCake/crud/pull/306

**Comment by ADmad** [comment]
Closing as related PR is merged.
