### ISSUE TITLE
Hiding Properties defined in $_hidden in the model Entity does not work

### ISSUE THREAD

**Issue by AndersTrier** [FriendsOfCake/crud#308]
In src/Model/Entity/Company.php I have added:
```php
protected $_hidden = ['password'];
```
However that does not work, and $event->subject()->entity->hiddenProperties(); returns null when called from within eg 'afterFind'.

But if I in 'afterFind' do something like:
```php
$event->subject()->entity->hiddenProperties(['password']);
```
It works. 

I think it is a bug, but it may just be me doing something wrong. Can anyone else confirm?

(Documentation http://book.cakephp.org/3.0/en/orm/entities.html#hiding-properties )

**Comment by AndersTrier** [comment]
It works fine. You just have to remember to load your model...
:blush:

**Comment by jadb** [comment]
LOL!
