### ISSUE TITLE
Handy event for accessible fields

### ISSUE THREAD

**Issue by steefaan** [FriendsOfCake/crud#313]
Maybe I overlooked something but I don't think so because I searched through the code for a while. It seems there is no handy place to change the accessible fields during save operations. I get it working for `Crud.Edit` with the following way:

```
        $this->Crud->on('afterFind', function(Event $event) {
            $event->subject->entity->accessible(['role_id', 'status'], true);
        });
```

but there are two things which are not so nice.

1. It's not nice to set the accessible fields when I load the edit form, because the changed fields are only ncessary during the save operation.
2. It won't work for `Crud.Add`, because there is no find before.

**Comment by jadb** [comment]
You haven't looked deep enough :wink: 

Use the `saveOptions` config, [here](https://github.com/FriendsOfCake/crud/blob/master/src/Action/AddAction.php#L52) and [here](https://github.com/FriendsOfCake/crud/blob/master/src/Action/EditAction.php#L52).

**Comment by steefaan** [comment]
Damn you was faster, I just found it :wink: .. but thanks. If someone is interested in:

```
$this->Crud->action()->saveOptions([
            'accessibleFields' => [
                'role_id' => true,
                'status' => true
            ]
        ]);
```

in your controller action is a possible way.

**Comment by jadb** [comment]
Maybe update the docs? :wink:

**Comment by steefaan** [comment]
Yes I will do a PR tomorrow.
