### ISSUE TITLE
Not able to get the Crud to work with Cakephp 3.0.12

### ISSUE THREAD

**Issue by smarek** [FriendsOfCake/crud#318]
Hi, 

with clean install of CakePHP through Composer
I've added `require friendsofcake/crud:~4.0`
I've added `Plugin::load('Crud');` within bootstrap.php
I've baked model and added Controller like this:

```php
<?php
namespace App\Controller;

class FucksController extends \Cake\Controller\AppController {

        use \Crud\Controller\ControllerTrait;

}
```

But launching the URL will let me see error like this:

![screen shot 2015-08-27 at 14 20 51](https://cloud.githubusercontent.com/assets/384824/9520355/da91e9aa-4cc6-11e5-8cf1-11191d9e5a63.png)

Thrown exception is correctly `Cake\Controller\Exception\MissingActionException` however Trait does not handle that.
I've also tried moving the ControllerTrait from FucksController to AppController, which did nothing.
When I removed `Plugin::load` it complained that CRUD plugin is not known.

Should it work like this or is there problem I've missed in install documentation? Thanks

**Comment by antograssiot** [comment]
@smarek `\Cake\Controller\AppController` doesn't exists. It either `\Cake\Controller\Controller` or `\App\Controller\AppController`

**Comment by smarek** [comment]
sorry, like this
```php
<?php
namespace App\Controller;

use App\Controller\AppController;

class FucksController extends AppController
{
    use \Crud\Controller\ControllerTrait;
}
```

**Comment by ADmad** [comment]
Quoting the docs:
>  Adding the ControllerTrait itself do not enable anything CRUD...

You need to configure the Crud component as explained here http://crud.readthedocs.org/en/latest/configuration.html

**Comment by alombd** [comment]
composer require friendsofcake/crud:^4.3
