### ISSUE TITLE
RequestHandlerComponent::viewClassMap() is deprecated

### ISSUE THREAD

**Issue by rachid804** [FriendsOfCake/crud#327]
This method is deprecated in Cakephp as mentioned in the book:

**Deprecated since version 3.1.0: As of 3.1.0 the viewClassMap() method is deprecated. You should use config() to change the viewClassMap at runtime.**

As a quick fix (or not) i commented the line 357 in ApiListener.php and my API still work fine until now.

Full error:
Deprecated (16384): RequestHandlerComponent::viewClassMap() is deprecated. Use config("viewClassMap", ...) instead. [CORE\src\Controller\Component\RequestHandlerComponent.php, line 706]
Code Context
Cake\Controller\Component\RequestHandlerComponent::viewClassMap() - CORE\src\Controller\Component\RequestHandlerComponent.php, line 706
Crud\Listener\ApiListener::injectViewClasses() - ROOT\vendor\friendsofcake\crud\src\Listener\ApiListener.php, line 357
Crud\Listener\ApiListener::render() - ROOT\vendor\friendsofcake\crud\src\Listener\ApiListener.php, line 190
Crud\Listener\ApiListener::respond() - ROOT\vendor\friendsofcake\crud\src\Listener\ApiListener.php, line 117
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Crud\Controller\Component\CrudComponent::trigger() - ROOT\vendor\friendsofcake\crud\src\Controller\Component\CrudComponent.php, line 505
Crud\Core\Object::_trigger() - ROOT\vendor\friendsofcake\crud\src\Core\ProxyTrait.php, line 37
Crud\Action\IndexAction::_handle() - ROOT\vendor\friendsofcake\crud\src\Action\IndexAction.php, line 57
Crud\Action\BaseAction::handle() - ROOT\vendor\friendsofcake\crud\src\Action\BaseAction.php, line 69
Crud\Controller\Component\CrudComponent::execute() - ROOT\vendor\friendsofcake\crud\src\Controller\Component\CrudComponent.php, line 228
App\Controller\Api\AppController::invokeAction() - ROOT\vendor\friendsofcake\crud\src\Controller\ControllerTrait.php, line 56
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37

**Comment by lorenzo** [comment]
Please make sure you have the latest version of this plugin

**Comment by lenanex** [comment]
It's the same for me, I've just installed the latest version of the plugin and cakephp and I get the same error : Deprecated (16384): RequestHandlerComponent::viewClassMap() is deprecated. Use config("viewClassMap", ...) instead. [CORE/src/Controller/Component/RequestHandlerComponent.php, line 710]

**Comment by ADmad** [comment]
@lenanex You shouldn't get that error if you have latest version. Check the exact plugin version you have using `composer show -i`

**Comment by lenanex** [comment]
The version I have installed is 4.1.4 (based on composer show -i).

**Comment by ADmad** [comment]
Show the full stack trace of error.

**Comment by lenanex** [comment]
Deprecated (16384): RequestHandlerComponent::viewClassMap() is deprecated. Use config("viewClassMap", ...) instead. [CORE/src/Controller/Component/RequestHandlerComponent.php, line 710]
Code Context
Cake\Controller\Component\RequestHandlerComponent::viewClassMap() - CORE/src/Controller/Component/RequestHandlerComponent.php, line 710
Crud\Listener\ApiListener::injectViewClasses() - ROOT/vendor/friendsofcake/crud/src/Listener/ApiListener.php, line 357
Crud\Listener\ApiListener::render() - ROOT/vendor/friendsofcake/crud/src/Listener/ApiListener.php, line 190
Crud\Listener\ApiListener::respond() - ROOT/vendor/friendsofcake/crud/src/Listener/ApiListener.php, line 117
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 355
Crud\Controller\Component\CrudComponent::trigger() - ROOT/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php, line 505
Crud\Core\Object::_trigger() - ROOT/vendor/friendsofcake/crud/src/Core/ProxyTrait.php, line 37
Crud\Action\IndexAction::_handle() - ROOT/vendor/friendsofcake/crud/src/Action/IndexAction.php, line 57
Crud\Action\BaseAction::handle() - ROOT/vendor/friendsofcake/crud/src/Action/BaseAction.php, line 69
Crud\Controller\Component\CrudComponent::execute() - ROOT/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php, line 228
App\Controller\AppController::invokeAction() - ROOT/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php, line 56
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37
Deprecated (16384): RequestHandlerComponent::viewClassMap() is deprecated. Use config("viewClassMap", ...) instead. [CORE/src/Controller/Component/RequestHandlerComponent.php, line 710]
Code Context
Cake\Controller\Component\RequestHandlerComponent::viewClassMap() - CORE/src/Controller/Component/RequestHandlerComponent.php, line 710
Crud\Listener\ApiListener::injectViewClasses() - ROOT/vendor/friendsofcake/crud/src/Listener/ApiListener.php, line 357
Crud\Listener\ApiListener::render() - ROOT/vendor/friendsofcake/crud/src/Listener/ApiListener.php, line 190
Crud\Listener\ApiListener::respond() - ROOT/vendor/friendsofcake/crud/src/Listener/ApiListener.php, line 117
Cake\Event\EventManager::_callListener() - CORE/src/Event/EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE/src/Event/EventManager.php, line 355
Crud\Controller\Component\CrudComponent::trigger() - ROOT/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php, line 505
Crud\Core\Object::_trigger() - ROOT/vendor/friendsofcake/crud/src/Core/ProxyTrait.php, line 37
Crud\Action\IndexAction::_handle() - ROOT/vendor/friendsofcake/crud/src/Action/IndexAction.php, line 57
Crud\Action\BaseAction::handle() - ROOT/vendor/friendsofcake/crud/src/Action/BaseAction.php, line 69
Crud\Controller\Component\CrudComponent::execute() - ROOT/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php, line 228
App\Controller\AppController::invokeAction() - ROOT/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php, line 56
Cake\Routing\Dispatcher::_invoke() - CORE/src/Routing/Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE/src/Routing/Dispatcher.php, line 87
[main] - ROOT/webroot/index.php, line 37

**Comment by ADmad** [comment]
I have made a new release which should fix this issue. The previous release did not contain updated code to avoid the deprecated error in Cake 3.1.

**Comment by lenanex** [comment]
Many thanks for your quick fix and congrats for this great plugin !
