### ISSUE TITLE
Docs on readthedocs.org not up to date.

### ISSUE THREAD

**Issue by ADmad** [FriendsOfCake/crud#328]
The page for new Search listener added in #315 is not listed in TOC for http://crud.readthedocs.org

/cc @jippi

**Comment by simkimsia** [comment]
I am trying to incorporate both Search 1.1.0 and Crud 4.2. 

I couldn't find any documentation on how to combine both, but I found this issue by accident.

I can help contribute to the docs, but at least I need someone to briefly describe to me how to use it

**Comment by davidyell** [comment]
The way I've done it was to write the controller actions which I needed to implement search in, and then returning the Crud execute.

**Comment by simkimsia** [comment]
@davidyell Any example code? I have created a PR that should make things clearer for search. https://github.com/FriendsOfCake/crud/pull/374 but personally I am still struggling to make it work in my own app.

**Comment by steefaan** [comment]
@simkimsia I have this in my AppController:

```
            ...
            'listeners' => [
                'Crud.Api',
                'Crud.RelatedModels',
                'Crud.Search'
            ]
            ....
```

```
        if (in_array($this->request->action, ['index', 'lookup'])) {
            $this->loadComponent('Search.Prg');
        }
```

It should work.

**Comment by simkimsia** [comment]
@steefaan I have a select2 field that wants to hit the end point http://example.app/companies?q= and the endpoint should return a .json of the search result

if this is the case, then in my CompaniesController class, I should have like yours
```
...
            'listeners' => [
                'Crud.Api',
                'Crud.RelatedModels',
                'Crud.Search'
            ]
            ....
```

in my index action should I still have 
```
    if (in_array($this->request->action, ['index', 'lookup'])) {
            $this->loadComponent('Search.Prg');
        }
```

And does that mean that the select2 should send a POST request?

And why `lookup` should also be considered as well?
