### ISSUE TITLE
Error when using offset in the Paginator settings

### ISSUE THREAD

**Issue by beez** [FriendsOfCake/crud#331]
I'm having the following code:
```$this->Crud->action()->findMethod('programs');
$this->Crud->on('beforePaginate', function (CakeEvent $event) use ($source, $tone) {
    $this->Paginator->settings['offset'] = Hash::get($this->request->query, 'offset');
});
return $this->Crud->execute();
```

When I do a request with ?limit=20 I've got 20 records all works as it should and in the response the following data is included:
`"pagination": {
    "page_count": 3,
    "current_page": 1,
    "has_next_page": true,
    "has_prev_page": false,
    "count": 55,
    "limit": 20
}`
In the QueryLog there are two queries: One with `LIMIT 20` and one count(*) without LIMIT. All as it should!

When I add a parameter for offset: `?limit=20&offset=20` it all works the same, the pagination is the same and the select query has `LIMIT 20, 20`

But when I do a request with `?limit=20&offset=40`, so that the returned number of records is less than the limit the the Pagination part looks like this:
`"pagination": {
    "page_count": 1,
    "current_page": 1,
    "has_next_page": false,
    "has_prev_page": false,
    "count": 15,
    "limit": 20
}`
And the QueryLog only has one select query with `LIMIT 40, 20`, the count query is missing…

I don't know why this is happening or if I'm doning anything wrong. If anyone have som suggestion on how to fix this I'll be glad to hear about it and if you have any question please ask. I'll try to se if I can come up with a fix for it…

**Comment by ADmad** [comment]
It's the paginator's job to calculate offset based on `page` you request and you shouldn't be specifying it yourself. You issue has nothing to do with Crud plugin itself.
