### ISSUE TITLE
Limit DeleteAction GET

### ISSUE THREAD

**Issue by steefaan** [FriendsOfCake/crud#338]
Other than expected it's possible to delete content with a normal GET request. I think we should limit this to POST/DELETE as suggested also for the normal cake delete action. What do you think?

**Comment by jippi** [comment]
You can it by either checking the action + request type in the controller, or only allow the router to access /delete using HTTP DELETE requests :)

**Comment by lorenzo** [comment]
I think this is not a bad idea to have by default

**Comment by adayth** [comment]
I was here to post the same issue. In Crud 3.0 was limited to DELETE / POST requests. I think the same behavior should be OK.

**Comment by adayth** [comment]
Meanwhile you could use a code in AppController like this to limit access to delete actions mapped with crud:
```php
public function beforeFilter(\Cake\Event\Event $event) 
{
        parent::beforeFilter($event);

        // Limit HTTP valid queries access to delete actions mapped with CRUD
        if ($this->request->action === 'delete'
            && $this->Crud->isActionMapped('delete')
            && !$this->request->is(['post', 'delete'])) {
            throw new MethodNotAllowedException();
        }
    }
```

**Comment by steefaan** [comment]
@adayth This is quite simpler:

```
        if (in_array($this->request->action, ['delete'])) {
            $this->request->allowMethod(['post', 'delete']);
        }
```

**Comment by adayth** [comment]
Thanks @steefaan !

**Comment by ADmad** [comment]
@steefaan Why use `in_array` for a static array with just one value? :)

**Comment by bravo-kernel** [comment]
:tractor:

**Comment by steefaan** [comment]
@ADmad Sorry was a copy paste from something like:

```
        if (in_array($this->request->action, ['index', 'lookup'])) {
            $this->Crud->addListener('Crud.Search');
            $this->loadComponent('Search.Prg');
        }
```

But yes you're right:

```
if ($this->request->action === 'delete') {
    $this->request->allowMethod(['post', 'delete']);
}
```

is enough here.

**Comment by ADmad** [comment]
Done in #346
