### ISSUE TITLE
Can not override the output type to json to acquire auto-generated response

### ISSUE THREAD

**Issue by martinkryl** [FriendsOfCake/crud#339]
Dear all, I was looking around for a solution to removing `.json` extension from a API url, and all the methods I have used in my beforeFilter (one is enabled, others commented out) have resulted in a error message of non-existent view. The app was looking in a `Users/json/` subdirectory though and when I created that view manually, it did output proper json.

When I use the same url with the `.json` extension, the auto-generation of the response works as expected.

I am using cakephp 3.1 and CRUD 4.

Here is my controller:
```php
<?php
namespace App\Controller\Api;

use Cake\Controller\Controller;
use Cake\Event\Event;

class UsersController extends Controller {

    use \Crud\Controller\ControllerTrait;

    //public $viewClass = 'Json';

    public $components = [
        'RequestHandler',
        'Crud.Crud' => [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'Crud.Api',
                //'Crud.ApiPagination',
                //'Crud.ApiQueryLog'
            ]
        ]
    ];

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        //$this->RequestHandler->ext = 'json';
        $this->RequestHandler->renderAs($this,   'json');
        //$this->viewClass = 'Json';
    }
}
```

**Comment by ADmad** [comment]
If not using .json extension then set `Accept` header in request to `application/json` only then will the `ApiListener` do it's "magic".

**Comment by martinkryl** [comment]
Great, thanks a lot! Sorry for bothering here.

**Comment by josegonzalez** [comment]
For anyone who wants to do this in the future, you can use the following:

```
$this->request->env('HTTP_ACCEPT', 'application/xml');
```
