### ISSUE TITLE
ApiQueryLog undefined method getLogs()

### ISSUE THREAD

**Issue by steefaan** [FriendsOfCake/crud#340]
If I load the ApiQueryLog listener I get sometimes the error message: `Fatal error: Call to undefined method DebugKit\Database\Log\DebugLog::getLogs() in /var/www/my_project/vendor/friendsofcake/crud/src/Listener/ApiQueryLogListener.php on line 83`

Maybe we should add [this](https://github.com/FriendsOfCake/crud/blob/master/src/Error/ExceptionRenderer.php#L124-L126) also for the ApiQueryListener [here](https://github.com/FriendsOfCake/crud/blob/master/src/Listener/ApiQueryLogListener.php#L83).

What do you think?

**Comment by josegonzalez** [comment]
Sounds good, pr?

**Comment by steefaan** [comment]
Yes I will do a PR for that and also for the other issue I opened but I'm not available during the weekend, so I will do it next week.
