### ISSUE TITLE
Replace assertTag with assertHtml

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#349]
So looking at this page, http://api.cakephp.org/3.1/deprecated.html, it seems the core have solved the problem with https://github.com/phpunit/phpunit-dom-assertions/issues/3

Cake\TestSuite\TestCase	assertTags()	3.0. Use assertHtml() instead.

**Comment by jippi** [comment]
PR Welcome :P

**Comment by t73biz** [comment]
Where in the test suites does the assertTags usage even occur? A quick search via Github within this repository does not even show any usages. ???

**Comment by davidyell** [comment]
Fair enough, I guess I got the wrong repo.
