### ISSUE TITLE
How does Crud plugin work with the native `bin/cake bake`?

### ISSUE THREAD

**Issue by simkimsia** [FriendsOfCake/crud#356]
I noticed while trying out the Crud plugin, I cannot use `bin/cake bake` as it is. 

This will create the controller indiscriminately.

Is there a way to cake bake a Controller ready for use with Crud?

**Comment by jippi** [comment]
Currently, no

Please submit a PR with a bake template for CRUD controllers :)

**Comment by steefaan** [comment]
I think a bake template for CRUD actions isn't really necessary regarding the nature of CRUD itself. A ready to use controller is an empty one, customizations really depend on the use case.

**Comment by simkimsia** [comment]
@jippi I like to try my hand at it.

How do I go about creating a bake template?

I found this http://book.cakephp.org/3.0/en/bake/development.html#creating-a-bake-theme

so I should put create a folder Template/Bake/Template inside the CRUD repo?

I am only concerned about cake3 by the way.

**Comment by simkimsia** [comment]
I sent in a pull request which I manage to get a trivial add action to work.

However, I would like to improve it further.

what's the difference between doing this for add

```
public function add()
    {
        return (new \Crud\Action\AddAction($this))->handle();
    }
```

and

```
	public function add() {
		$this->Crud->listener('relatedmodels')->relatedModels(['posts']);
		return $this->Crud->execute();
	}
```

**Comment by simkimsia** [comment]
#365 fixes the bake for add action.

Left with edit, delete, view, and index
