### ISSUE TITLE
Is there a way to change the finder query for the related models?

### ISSUE THREAD

**Issue by simkimsia** [FriendsOfCake/crud#364]
Assuming a Post hasMany Comments and A Comment belongsTo Post, 

```
public function add()
    {
        // Automatically executes find('list') on the 
        // associated tables that are either BelongsTo or BelongsToMany
        $this->Crud->listener('relatedModels')->relatedModels(['Posts']);
        
        return $this->Crud->execute();
    }
```

I want to be able to change the condition of the finder for the Posts. E.g. I only want to find those Posts which are active.

**Comment by ADmad** [comment]
Use the [relatedModel event](http://crud.readthedocs.org/en/latest/listeners/related-models.html#events) as stated in the docs.

**Comment by simkimsia** [comment]
Thank you. I got it.
