### ISSUE TITLE
Actions bypassing Auth :(

### ISSUE THREAD

**Issue by commercial-hippie** [FriendsOfCake/crud#366]
I have no actions mapped in my AppController and instead just setting up actions in the controller initialize method. (`this->Crud->mapAction('index', 'Crud.Index');`)

[AuthComponent doesn't work though because there is no action found here.](https://github.com/cakephp/cakephp/blob/7af88180ed3a222a495f1c10bb21a58ec039c955/src/Controller/Component/AuthComponent.php#L280)

**Comment by commercial-hippie** [comment]
Similar: https://github.com/FriendsOfCake/crud/issues/189

**Comment by jippi** [comment]
have you loaded the Crud Controller trait?

https://github.com/FriendsOfCake/crud/blob/master/src/Controller/ControllerTrait.php#L74

**Comment by commercial-hippie** [comment]
Yup!

I was loading the auth component first with `'checkAuthIn' => 'Controller.initialize'`, and then after that crud.

Loading crud before loading the auth component fixed the issue for now.
