### ISSUE TITLE
[Question] How is the validation method inside the ExceptionRenderer being used?

### ISSUE THREAD

**Issue by simkimsia** [FriendsOfCake/crud#367]
I am taking inspiration from the ExceptionRenderer but I noticed that this validation function

https://github.com/FriendsOfCake/crud/blob/master/src/Error/ExceptionRenderer.php#L27

does not have its equivalent in the parent class it extends from aka cakephp\cakephp\src\Error\ExceptionRenderer.php aka Cake\Error\ExceptionRenderer

Can help me understand how this method is being used?

Because I think it is not called at all.

**Comment by steefaan** [comment]
@simkimsia It is called when you use the ApiListener.

**Comment by simkimsia** [comment]
thank you.
