### ISSUE TITLE
API Listener working when not activated

### ISSUE THREAD

**Issue by raul338** [FriendsOfCake/crud#369]
I have a ProductsController and a SuppliersController. Both using Crud almost with no configuration (only the before/after Find/Paginate events)

I added the ```Router::extensions(['json', 'xml']);``` line and went to http://localhost:8765/products/view/1.json and http://localhost:8765/suppliers/view/1.json and BOTH worked, just print out the json like the API Listener would be invoked, but I didn't added the listener yet!

I don't know if this behavior is a bug. I just want to Products to have the API listener, not Suppliers.
Am I doing it right?

**Comment by ADmad** [comment]
What's the exact crud config you are using?  How did you conclude ApiListener is executed?

**Comment by lorenzo** [comment]
If you added the RequestHandlerComponent, then you are hitting the automatic API feature of CakePHP

**Comment by ADmad** [comment]
Yup, that seems to be the case.

**Comment by raul338** [comment]
Yep, the RequestHandlerComponent was loaded in the AppController, just moved to the ProductsController. Sorry about that.

But now a little issue (i think it must be a new issue in cakephp)... if i go to 
http://localhost:8765/suppliers/view/1 and http://localhost:8765/suppliers/view/1.json i get the same result in html. Is there any way to throw like a 400 error or something? My routes looks like this

```php
Router::scope('/', function ($routes) {
    $routes->extensions(['json']);
    $routes->resources('Products');

    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    $routes->fallbacks('DashedRoute');
});
```

Thanks!

**Comment by ADmad** [comment]
Don't post an issue on cakephp's tracker as it's an implementation problem not a bug. Post your question on stackoverflow.com or ask on `#cakephp` IRC channel.

**Comment by josegonzalez** [comment]
@ADmad not cakephp's tracker ;)
