### ISSUE TITLE
Configuring findMethod for ViewAction

### ISSUE THREAD

**Issue by pedrofs** [FriendsOfCake/crud#382]
Hi guys,

I'm trying to configure the `findMethod` for the `ViewAction` but it calls the `findMethod` passing no `options`.

I've done this as:
```php
$this->Crud->action()->config('findMethod', 'view'); 
```

But as I said no `options` are passed as argument to my `view` method.

In this specific case I'm trying to look for both `id` OR `slug` properties for the given `id` passed to my view action.

Thanks!

**Comment by pedrofs** [comment]
For now I'm changing the query through `Crud.beforeFind` adding a call to `orWhere`.

Just wondering if having the `options` passed in to my custom finder wouldn't make the code clearer and well testable.

Cheers.

**Comment by josegonzalez** [comment]
The code for that is [here](https://github.com/FriendsOfCake/crud/blob/master/src/Traits/FindMethodTrait.php#L34).

Ideally, what does the external interface for setting options look like, and how would that work in relation to how the query is constructed in the above method?

**Comment by pedrofs** [comment]
After carefully check this method I see it wouldn't work.

Thanks for your attention.
