### ISSUE TITLE
[Docs] Prefix routing

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#393]
Need some examples of using Crud just inside a prefix. In my project that I'm using as reference I've just created a new controller, which extends `AppController` and then configured it in the child controller.

If it's possible to pass routing prefixes into the configuration then we should document that. Such as just running Crud on `admin` prefixes only.

**Comment by bravo-kernel** [comment]
Out of curiosity... is that even possible/needed? I am extensively using (namespaced) prefixes in my API. In my prefixed namespaces I  now either:

- extend AppController in main namespace (when I want to use/share the main CRUD config)
- set up CRUD in the AppController belonging to the prefixed namespace (when I need prefix specific CRUD setup)

**Comment by dingonv** [comment]
I may have done what you were asking about.
my prefix is /api
in src/Controller i created a folder: Api
in there i created a new AppController with 
namespace App\Controller\Api;

i then created all my api controllers in there. Crud is only loaded in that controller.
my routes also look like this, before Router::scope()
Router::prefix('api', function($routes) {
	
	$routes->extensions(['json', 'xml']);
	$routes->resources('Users');
	
 	Router::connect('/api/users/:id/:action',['controller' => 'Users', 'action' => 'reset', 'prefix' => 'api'], ['id' => '[0-9]+'] );
    Router::connect('/api/users/register', ['controller' => 'Users', 'action' => 'add', 'prefix' => 'api']); 
	$routes->fallbacks('InflectedRoute');
	
});

I'm not entirely sure that covers what you were asking for, but it works for me.

**Comment by ADmad** [comment]
As @dingonv said make an AppController for your prefix and load CrudComponent in that. Then all other controllers of that prefix extend it. Done!

**Comment by davidyell** [comment]
Great that we have the solution. I'm reopening so someone can add it to the docs.
