### ISSUE TITLE
Crud subject

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#394]
There are some broken references in the documentation on the `actions` page which refer to 

```
:ref:`Crud Subject`<crud-subject>`
```

However there isn't an internal section with this reference. Is it worth creating a new page for the Crud Subject class or expanding it's description in the events page? I think it would hold value as many of the callback methods such as `beforeFilter` rely on making changes to the Crud Subject class, such as updating pagination parameters.

However the [classes docblocks are sparse](https://github.com/FriendsOfCake/crud/blob/master/src/Event/Subject.php) and as the subject will contain different things for different actions, I think it will bring value to help users understand what this class does, what it will contain in most common cases, and how they can change it to effect changes in the Crud scaffolding.

It seems that some of the subject docs are interwoven into the Actions pages, and this might be why there is a missing label, if the Crud Subject section is missing from each action page.

**Comment by bravo-kernel** [comment]
Good idea, the one thing that totally confused me when starting with CRUD was the fact that subject contains different things depending on the action, e.g.

- when using `index` action I need to use `$subject()->query`
- when using `view` action I need to use `$subject->entity`

Makes total sense to me now but wish I could have had that explained, ideally with an example.

One more thing about the subject; it seems that I can use both `$event->subject()` and `$event->subject`. Could be something I am doing wrong but if the latter is valid using that as the documented variation would have my preference.

**Comment by davidyell** [comment]
I'd be interested in getting some feedback on the current, quite sparse, page.

http://crud.readthedocs.org/en/latest/crud-subject.html

I feel that replicating all the event subject data here would be too much duplication though. It could be broken out into partials which could be included in both the Subject page and the Events pages though.

Otherwise, if we're happy with it, I can close this issue.

**Comment by Spriz** [comment]
IMO this page is sufficient in it's current state.

**Comment by inoas** [comment]
What would be good is explaining more thoroughly what this subject is or can be.

**Comment by davidyell** [comment]
As I've not progressed this in the time it was assigned to me. I'll try and get back to it at some stage.
