### ISSUE TITLE
[Docs] Copyright to Friends of Cake?

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#395]
I noticed in the `conf.py` file that the copywright message is 

```python
copyright = u'2014, Christian Winther'
```

@jippi would you be okay if I changed this to Friends of Cake? As the software license is MIT

**Comment by jippi** [comment]
@davidyell yeah, remove my name and put FoC :)

**Comment by bravo-kernel** [comment]
:clap:
