### ISSUE TITLE
useModel

### ISSUE THREAD

**Issue by wadeos** [FriendsOfCake/crud#399]
When using the useModel method on the Crud Component.

I get the notice, trying to get property of non-object on line 574.
Looking back at the develop branch, I can see that is has changed from using list and pluginSplit to setting the model name to using a class property which doesn't exist now.

Is this a intentional?

**Comment by ADmad** [comment]
While `CrudComponent::useModel()` can be fixed, I am not sure it will serve any purpose. The action classes use `ProxyTrait::_table()` to get table instance which calls [Controller::loadModel()](https://github.com/FriendsOfCake/crud/blob/master/src/Core/ProxyTrait.php#L114) with 1st param as `null`, hence whatever model name you set using `CrudComponent::useModel()` becomes irrelevant and `Controller::$modelClass` will be always used.

There's only `CrudComponent::table()` which uses `CrudComponent::$_modelName` but I don't think that method is used by action classes. So perhaps we should just deprecate / remove CrudComponent::useModel()` and CrudComponent::table()`.

**Comment by wadeos** [comment]
Will there be a method of changing the model once deprecated?

As I have a plugin which uses crud for the controllers and models from the base application. 

So if I don't use useModel, I cannot load any associations as the table class that has been loaded within the plugin is a generic fallback one rather than the actual. 

I have changed the useModel to the previous implementation which works with my use case above.

```php 
$this->_controller->loadModel($modelName);
list(, $modelName) = pluginSplit($modelName);
$this->_modelName = $modelName;
```

Any ideas?

**Comment by Laykou** [comment]
I also came across this problem.

So is there any solution to use the `Curd` for other than default model inside a controller?

**Comment by Laykou** [comment]
I mean the only solution/workaround now is to change the controller's `$this->modelClass = 'AnotherTable'`, right?

**Comment by wadeos** [comment]
To get crud to use another model, call the useModel method on the crud component. As shown below.

```php
$this->Crud->useModel('AnotherTable');
```
