### ISSUE TITLE
API listener overrides custom-set ExceptionRenderer

### ISSUE THREAD

**Issue by curtisgibby** [FriendsOfCake/crud#407]
In **ApiListener::registerExceptionHandler()**, the $exceptionRenderer is hard-coded to use this plugin's exception renderer, `'Crud\Error\ExceptionRenderer'` and completely ignores anything that the user has set in their app.php config for the exception renderer.

I think this behavior should be modified to check to see if the user-specified exception renderer class is a subclass of CRUD's ExceptionRenderer, and if so, use that rather than the hard-coded version. I'd like to be able to extend Crud\Error\ExceptionRenderer (i.e. App\Error\CustomExceptionRenderer extends Crud\Error\ExceptionRenderer).

**Comment by bravo-kernel** [comment]
Is the above claim correct, e.g. no other way to specify a custom ExceptionRenderer?

If so, would a PR to set a different ExceptionRenderer class be welcome?

**Comment by ADmad** [comment]
@bravo-kernel It's correct :)  Simple fix would be to add a config `exceptionRenderer` to `ApliListener` with default value `'Crud\Error\ExceptionRenderer'`. User can then change it as needed.

**Comment by bravo-kernel** [comment]
Thought so, thanks for confirming. I will give this a shot.

**Comment by curtisgibby** [comment]
If you change [this line](https://github.com/FriendsOfCake/crud/blob/f95e7a0250a0840b23759636131fec553ade5eda/src/Listener/ApiListener.php#L156) to use `array_merge` instead of the array union `+` operator, then the user-configured `exceptionRenderer` would be used.

However, I think that you'd want to make sure that you don't lose the functionality of CRUD's exception renderer, which is why I suggested that you check to see if the configured exceptionRenderer extends the CRUD version.

**Comment by bravo-kernel** [comment]
@curtisgibby I don't need that functionality but could passing the `exceptionRenderer` value found in `app.php` into the new config option (in the PR) solve your problem?

**Comment by curtisgibby** [comment]
Yes I think so.

**Comment by bravo-kernel** [comment]
Nice, then all we need to now is cross :v: and hope for a merge

**Comment by curtisgibby** [comment]
Oh, is the PR done? I thought you weren't finished with it yet, since I don't see where it actually affects the function in question. **ApiListener::registerExceptionHandler()** still always uses `Crud\Error\ExceptionRenderer` regardless of what the user configures.

**Comment by bravo-kernel** [comment]
https://github.com/FriendsOfCake/crud/pull/420/files#diff-cd0f7e3ff2db9da3edd6a923634d2049R156

**Comment by bravo-kernel** [comment]
In all honesty, I forgot to commit the crucial line :fish:

**Comment by ADmad** [comment]
Closing as PR is opened.
