### ISSUE TITLE
About i18n

### ISSUE THREAD

**Issue by raul338** [FriendsOfCake/crud#412]
Can someone pelase give me a clue of how put crud messages in a .po file ?
Tried to extract it using i18n shell but only got this, not all the messages (like successfull add)

```
#: Error/Exception/ValidationException.php:42
msgid "A validation error occurred"
msgid_plural "{0} validation errors occurred"
msgstr[0] "Hay un error de validación"
msgstr[1] "Hay {0} errores de validación"
```

I know I can modify some messages in the config key in the action while loading the plugin, but that doesn't feel so DRY.

Also (this should be apart, I think is not crud related) how to "translate" the human name of the model.

This should be added to the docs

**Comment by raul338** [comment]
I realized that make a call to __d function, so you can have a `crud.po` file with the following content.
You just have to replace {name} to your model human name and repeat it for all your models that use crud. I've included the bulk action messages too. You can change the message and/or filename via action configuration (messages and domain)
```
# Add action
msgid "Successfully created {name}"
msgstr ""

msgid "Could not create {name}"
msgstr ""

# Edit action
msgid "Successfully updated {name}"
msgstr ""

msgid "Could not update {name}"
msgstr ""

# Delete action
msgid "Successfully deleted {name}"
msgstr ""

msgid "Could not delete {name}"
msgstr ""

# Bulk Delete
msgid "Delete completed successfully"
msgstr ""

msgid "Could not complete deletion"
msgstr ""

# Bulk SetValue
msgid "Set value successfully"
msgstr ""

msgid "Could not set value"
msgstr ""

# Bulk Toogle
msgid "Value toggled successfully"
msgstr ""

msgid "Could not toggle value"
msgstr ""
```

**Comment by davidyell** [comment]
Great, I'm glad you managed to work it out. I'll re-open this ticket so that we can add it to the documentation for others to find.

**Comment by berarma** [comment]
Where's the documentation?

It would be convenient having a way to automatically generate a POT file.
