### ISSUE TITLE
API bulk actions returning true even if some records aren't updated

### ISSUE THREAD

**Issue by aceat64** [FriendsOfCake/crud#416]
When bulk actions are performed if any rows are updated then `success` is true, if no rules are updated `success` is false.

I think it would make sense for `success` to be false if only some of the records were updated, and then have `data` provide a message stating that the update was partially successful and showing the count of how many records were updated.

Ideally we'd show the ids of which records weren't updated, but I think that would require a 2nd query and some overhead.

Thoughts?

**Comment by lorenzo** [comment]
Maybe it should be a mode flag? I think I prefer the current default

**Comment by davidyell** [comment]
To me, the ideal situation would it returning an array of errors which data which failed to update instead of false, this would allow the developer to address the fail condition in a more concise way.

**Comment by josegonzalez** [comment]
Going to reopen this. I believe it should be done, someone just has to sit down and write the code.

**Comment by bravo-kernel** [comment]
I could certainly use this feature for singe `add` as well as this would complement the jsonapi spec.
