### ISSUE TITLE
Load Custom action classes via component doesn't seems working

### ISSUE THREAD

**Issue by LoveMyData** [FriendsOfCake/crud#418]
If I load custom action class via load component, it doesn't seems to be working

```php
    public function initialize()
    {
        parent::initialize();

        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'index' => ['className' => '\App\Crud\Action\MyIndexAction']
            ]
        ]);
    }
```

need to add mapAction

```php
  public function beforeFilter(\Cake\Event\Event $event)
  {
      $this->Crud->mapAction('index', '\App\Crud\Action\MyIndexAction');
  }
```

to make it work

**Comment by josegonzalez** [comment]
Some investigation:

```php
$this->loadComponent('Crud.Crud', []);
$this->Crud->mapAction('view', '\App\Crud\Action\MyViewAction');
$mapped = $this->Crud->isActionMapped('view'); // true;


$this->loadComponent('Crud.Crud', [
    'view' => [
        'className' => '\App\Crud\Action\MyViewAction',
    ]
]);
$mapped = $this->Crud->isActionMapped('view'); // null;

$this->loadComponent('Crud.Crud', [
    'view' => [
        'className' => '\App\Crud\Action\MyViewAction',
        'enabled' => true,
    ]
]);
$mapped = $this->Crud->isActionMapped('view'); // null;
```

Seems like we need to at least update the docs. FWIW, the `enabled` option is set to true in the core crud actions classes.

**Comment by ADmad** [comment]
@LoveMyData Do you have `'enabled' => true` in your action class' `$_defaultConfig` ?

**Comment by LoveMyData** [comment]
Hi @ADmad, no, I followed the online doc
http://crud.readthedocs.org/en/latest/actions/custom.html and there is no
where mention about the 'enabled' => true

**Comment by ADmad** [comment]
Okay, so that's the cause of your issue. Without `'enabled' => true` in `$_defaultConfig` you will have to use `$this->Crud->enable('index')` to explicitly enable it.  Using `mapAction()` worked for you cause by default it also enables the action as setting it up (the 3rd argument of `mapAction()` controls that).

Would you like to make a PR updating the docs stating that one should have `'enabled' => true` in `$_defaultConfig` to avoid having to explicitly enable it?

**Comment by ADmad** [comment]
I updated the docs example.

**Comment by htstudios** [comment]
Also if you simply specify a namespace that is not correct CRUD custom action configuration will fail silently.

**Comment by josegonzalez** [comment]
@htstudios mind updating the docs for that?
