### ISSUE TITLE
Create record on PUT if ID doesn't exist

### ISSUE THREAD

**Issue by DVassilev** [FriendsOfCake/crud#419]
Hello,

Is it possible to configure it such that if you were to PUT to /entity/2 where no record existed with ID 2 it would then create it?

Thanks,
Daniel

**Comment by bravo-kernel** [comment]
That would be poor design and against [RFC1616 specification for PUT](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) IMHO.

>The fundamental difference between the POST and PUT requests is reflected in the different meaning of the Request-URI. The URI in a POST request identifies the resource that will handle the enclosed entity. That resource might be a data-accepting process, a gateway to some other protocol, or a separate entity that accepts annotations. **In contrast, the URI in a PUT request identifies the entity enclosed with the request** -- the user agent knows what URI is intended and the server MUST NOT attempt to apply the request to some other resource. If the server desires that the request be applied to a different URI

Shameless copy of first stackoverflow hit.

**Comment by thinkingmedia** [comment]
> If the Request-URI does not point to an existing resource, and that URI is capable of being defined as a new resource by the requesting user agent, the origin server can create the resource with that URI. If a new resource is created, the origin server MUST inform the user agent via the 201 (Created) response

What @DVassilev is asking for is exactly what the specification states.

I don't see how that is poor design?

**Comment by bravo-kernel** [comment]
@thinkingmedia I stand corrected if the RFC says so :relaxed: Never realized/read that before, probably read over it.

**Comment by DVassilev** [comment]
That's alright, would you know how to do this? Would be nice to have a 
configuration for Crud that would make it comply to the specs.

**Comment by thinkingmedia** [comment]
You probably are confusing PUT with PATCH

**Comment by thinkingmedia** [comment]
For most people, if you PUT to a URL `/thing/3` and the record does not exist then it was likely a developer mistake.

The majority of database tables use auto-incrementing IDs or UUID, and are generated at the time of inserting records. Having a REST end point that defines the ID for new records is not common practice.

As a default implementation CRUD should reject PUT requests that don't have a record.

If you require this feature. You should add it yourself, and it will likely only be fore a few models.

**Comment by bravo-kernel** [comment]
@thinkingmedia exactly my point :arrow_up:

**Comment by thinkingmedia** [comment]
@bravo-kernel why didn't you just say so? :laughing:

**Comment by bravo-kernel** [comment]
I thought I was clear enough, learned another thing :wink:

**Comment by DVassilev** [comment]
Quote from the doc linked above: " If the Request-URI does not point to an 
existing resource, and that URI is capable of being defined as a new 
resource by the requesting user agent, the origin server can create the 
resource with that URI. If a new resource is created, the origin server 
MUST inform the user agent via the 201 (Created) response".
It is similarly recommended on the Wikipedia page for RESTful APIs.
