### ISSUE TITLE
RFC: Bulk edit action

### ISSUE THREAD

**Issue by Spriz** [FriendsOfCake/crud#424]
Hi there!

It seems like it's pretty normal with a "bulk edit" REST endpoint, so I was thinking to implement it as a CRUD action, but wanted to ask if there was any specific reason why it's not already there?

I was thinking more or less to throw request data directly to `patchEntities()`

**Comment by Wouter0100** [comment]
Because of security concerns? I can understand why they wouldn't implement that. Instead, they've implemented `bulkSetValue`.

**Comment by Spriz** [comment]
Might be the reason, but I'm not sure why it's more of a security concern to bulk edit a bunch of entities rather than using `SetValue` action?

**Comment by josegonzalez** [comment]
It's not there because no one wrote it. I wrote SetValue because I needed it for crud-view.

**Comment by Spriz** [comment]
Doesn't sound like there's any particular reasons - I'll put together a PR. :)
