### ISSUE TITLE
FindMethodTraid::_findRecord() don't works if table have composite keys.

### ISSUE THREAD

**Issue by alysson-azevedo** [FriendsOfCake/crud#431]
In the [line 39](https://github.com/FriendsOfCake/crud/blob/master/src/Traits/FindMethodTrait.php#L39), the `current($query->aliasField($repository->primaryKey()))` returns an array.

Here's the error:
```
Warning (2): strpos() expects parameter 1 to be string, array given [CORE/src/Datasource/QueryTrait.php, line 210]
Warning (2): explode() expects parameter 2 to be string, array given [CORE/src/Datasource/QueryTrait.php, line 214]
Warning (2): Illegal offset type [ROOT/vendor/friendsofcake/crud/src/Traits/FindMethodTrait.php, line 39]
```

Is there a way to handle it?

**Comment by lorenzo** [comment]
No, there is not. In cases like this I have done my own Action class.

You are also welcome to submit a pull request for fixing your issue

**Comment by alysson-azevedo** [comment]
Well, i also created my own action class, but if change the FindMethodTrait->findRecord() to do the same thing Table->get() does, it will be nice.

I'll prepare a pull-request.

**Comment by alysson-azevedo** [comment]
Pull-request open.
