### ISSUE TITLE
Related Models Listener set a query instead of an array

### ISSUE THREAD

**Issue by raul338** [FriendsOfCake/crud#434]
In 4.3.2 (and before) the related models listener set the variables as an array instead of the original query object, this changed in 4.3.3 and I think it is due the changes in [commit f481787](https://github.com/FriendsOfCake/crud/commit/f481787ebd90e6e553d87bee47d281858388abe0#diff-7da0c48b2d3d51f2eb66ca3027de1bc1R99)

Updating from 4.3.2 to 4.3.3 this call `$newslists[$campaign->newslist_id]` ($newslists is the related model) now throw this exception
`Cannot use object of type Cake\ORM\Query as array`

**Comment by davidyell** [comment]
Yeah looks like @jippi removed the `toArray()` call. Good spot.

**Comment by jippi** [comment]
oopsie doopisie - added back in dev-master
