### ISSUE TITLE
Exceptions doesn't keep http headers in cross domain ajax response

### ISSUE THREAD

**Issue by irongomme** [FriendsOfCake/crud#436]
Everything is good until response code is 200. But with exceptions (eg 401, 403), all http headers are cleared in http response, which cause the browser to alert me on CORS issue : 

```
XMLHttpRequest cannot load http://api.mydomain.dev/api/users/login. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mydomain.dev' is therefore not allowed access. The response had HTTP status code 401.
```

And i don't know what to do to fix it. When i disable this plugin, all works fine.

**Comment by ADmad** [comment]
CakePHP creates a new response instance for exceptions hence all your headers are lost. You can fix that by setting CORS headers in a dispatcher filter's afterDispatch() callback.
