### ISSUE TITLE
Timestamp Behavior with edit action

### ISSUE THREAD

**Issue by irongomme** [FriendsOfCake/crud#442]
I'm using a ModelTable with a Timestamp Behavior which work in add action by auto generating the created and modified field. But in edit action, the modified field is not updated, so i have to add this code : 

```
public function edit()
    {
        $this->Crud->on('beforeSave', function (\Cake\Event\Event $event) {
            $event->subject()->entity->modified = Time::now();
        });

        return $this->Crud->execute();
    }
```

Is there anything i've missed ?

**Comment by Spriz** [comment]
this should very well be handled only in the table class @irongomme :) Were you able to solve this?

**Comment by irongomme** [comment]
It actually works as expected with up to date cake & crud
