### ISSUE TITLE
Class 'Object' not found

### ISSUE THREAD

**Issue by themrwilliams** [FriendsOfCake/crud#453]
Using the 3.x (for Cake 2.x) version of crud on Cake 2.9 and possibly earlier results in the following error:

Fatal error: Class 'Object' not found in /path/to/app/Plugin/Crud/Controller/Crud/CrudBaseObject.php on line 14

I think this is because when Cake renamed Object to CakeObject and aliased it with class_alias() they stopped explicitly loading a class called Object, which crud requires.  Adding an App::use() call to the plugin should resolve this.

**Comment by josegonzalez** [comment]
Thanks for this pr!
