### ISSUE TITLE
Combined setter/getter split

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfCake/crud#462]
How do you feel to also do the split into own methods for setting and getting?
For a cleaner API and less error-prone access.
It also makes typehinting more strict, so it is clearer what types are expected to go in or come out.

Keeping the old methods makes this BC and can be done at any time.

**Comment by jippi** [comment]
I'm personally opposed to this java-craze :)

**Comment by josegonzalez** [comment]
If that is the way the cakephp core is headed, then I would be 👍 for that, since it makes our usage similar to the core's, which is helpful when switching back and forth.

**Comment by dereuromark** [comment]
The craze is actually the current Code :) and you should know that.

**Comment by jippi** [comment]
I'm personally opposing this kind of change for change sake, it adds very little value to the current code, but will eventually result in breaking change if we mark it as deprecated. 

i don't think the value of the change outweigh the eventual work required by our users to change their code just to satisfy a new php-craze in how things should be done.. in 3 years someone will PR "merge set/get for simplicity" 

If you add the set/get as an additional part of the interface, and letting the users opt in to whatever they prefer, without marking the old as deprecated, I'm all for it though :)

**Comment by dereuromark** [comment]
We shouldnt have both ways.
The combined ones are very bad for a lot of reasons, also for future possibility to further strictly typehint methods. See the core tickets for this on the reasoning why this is long overdue to get rid of.
Just sticking to it for the sake of it does not sound sane to me.
We should focus on a good API - and it will be 100% BC, why would you think otherwise?

**Comment by davidyell** [comment]
I'm 👍  on this.

Change for changes sake aside, this is a sane direction to travel in. It takes us away from combined get/set/return type methods and also neatly sidesteps the potential for magic methods.

**Comment by dereuromark** [comment]
So if someone would actually do the work, is there a change that this will actually be accepted?
