### ISSUE TITLE
API Listener not returning validation errors

### ISSUE THREAD

**Issue by pedro-stanaka** [FriendsOfCake/crud#465]
I am using version 4.3 of Crud and when I try to create a new record, if it has validation errors there is no data attribute in my json as the [docs](http://crud.readthedocs.io/en/latest/listeners/api.html#http-post-add) suggest. 

Example of return:

```json
{
  "message": "A validation error occurred",
  "url": "/api/users/register",
  "code": 422
}
```

If it helps, I'm kind of following this tutorial: http://www.bravo-kernel.com/2015/04/how-to-add-jwt-authentication-to-a-cakephp-3-rest-api/ 

I tried to set the data view variable by hand, but no luck. Is this behavior expected? 

By the little research I've done it seems that the plugin is ignoring all configuration and returning only the content of the exception Crud\Error\Exception\ValidationException.

**Comment by ADmad** [comment]
Did you update your config/app.php to use Crud's ExceptionRenderer as stated in the [docs](http://crud.readthedocs.io/en/latest/listeners/api.html#exception-handler) ?

**Comment by pedro-stanaka** [comment]
Oooops guys, @ADmad I did not mean by any means to be rude. Thanks for the help. It worked.
