### ISSUE TITLE
Loosing relatedModel id on a add action

### ISSUE THREAD

**Issue by irongomme** [FriendsOfCake/crud#466]
I'm trying to save an new object with an existing related object. Here is raw data submitted : 

```
[
	'member_id' => (int) 1,
	'customer_id' => (int) 1,
	'feature' => [
		'id' => (int) 1,
		'project_id' => (int) 6,
		'name' => 'Test',
		'created' => '2016-12-27T13:44:13+00:00',
		'modified' => '2016-12-27T13:44:13+00:00'
	],
	'started_on' => '2016-12-28 09:00:00',
	'ended_on' => '2016-12-28 12:30:00'
]
```

And here is what it is sent to the Crud plugin : 

```
public function add()
    {
        $this->Crud->on('beforeSave', function (\Cake\Event\Event $event) {
            debug($event->subject()->entity->feature);exit;
        });

        return $this->Crud->execute();
    }
```

Which give me : 

```
object(App\Model\Entity\Feature) {

	'project_id' => (int) 6,
	'name' => 'Test',
	'created' => '2016-12-27T13:44:13+00:00',
	'modified' => '2016-12-27T13:44:13+00:00',
	'[new]' => true,
	'[accessible]' => [
		'*' => true
	],
	'[dirty]' => [
		'project_id' => true,
		'name' => true,
		'created' => true,
		'modified' => true
	],
	'[original]' => [],
	'[virtual]' => [],
	'[errors]' => [],
	'[invalid]' => [],
	'[repository]' => 'Features'

}
```

Field ID have disappeared, and then it is saved as a new object, because it is seen as a new entry by Crud Plugin. Have i missed something or is there a bug ?

**Comment by ADmad** [comment]
What is the association between the table who's entity you are saving and `Features` table?

**Comment by irongomme** [comment]
I have a TimeLogsTable : 

```
$this->belongsTo('Features', [
            'foreignKey' => 'feature_id'
]);
```

and a FeaturesTable : 

```
$this->hasMany('TimeLogs', [
            'foreignKey' => 'project_id'
]);
```

And i'm trying to save a TimeLog entry, with a Feature linked entry, which can be new or existing. When the feature entry is new, everything is alright, but when it already exists, the feature entry is added anyway.

**Comment by ADmad** [comment]
If you want to link an existing feature then you should set the feature_id property for the timelog entity.

Your issue is unrelated to the Crud plugin, it's how the ORM works.

**Comment by irongomme** [comment]
Ok, thanks !
