### ISSUE TITLE
Column 'created' in order clause is ambiguous

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#474]
## My Setup
`WorkLogs belongsTo Companies`
Companies has `created` and `modified`, and so does `WorkLogs`.

## What I did
I added the `Crud.RelatedModels` listener to my configuration and enabled all related models.

```php
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'index' => [
                    'className' => 'Crud.Index',
                    'relatedModels' => true
                ],
// etc
```

## What's happening
I'm getting an ambiguous field error in SQL because the fields being selected are not using `aliasField()`.

## How to fix
Not too sure, as there is no `select()` in the listener to process the fields. Short of getting the schema, and looping through the fields and calling `aliasField()` which seems dirty.

## Sidestep
I'll just create my own index method for the meantime.

**Comment by jippi** [comment]
PR is welcome to fix this issue :)

**Comment by davidyell** [comment]
![Whoops](https://media.giphy.com/media/ohyNdetcfoJ9K/giphy.gif)

I was looking in the wrong controller.
