### ISSUE TITLE
Documentation search links incorrectly to results

### ISSUE THREAD

**Issue by eaxexe** [FriendsOfCake/crud#480]
When searching the documentation, all results found are linked to incorrectly.

[Example link](http://crud.readthedocs.io/en/latest/search.html?check_keywords=yes&area=default&q=bake)

The found links looks like:
http://crud.readthedocs.io/en/http://crud.readthedocs.io/en/latest/quick-start

Having the `http://crud.readthedocs.io/en/` in the middle, and a missing .html at the end.

This results in the links not working at all.

**Comment by bravo-kernel** [comment]
@jippi search links are indeed broken. Is this something we can fix inside this repo?

**Comment by jippi** [comment]
I guess, no idea how to fix it though :P

**Comment by ADmad** [comment]
@savant Could you please look into this?

**Comment by josegonzalez** [comment]
Fixed by https://github.com/cakephp/docs-theme/releases/tag/1.0.2

**Comment by bravo-kernel** [comment]
👏

**Comment by eaxexe** [comment]
👍  Nice!
