### ISSUE TITLE
[vulnerability] Crud.Lookup column access

### ISSUE THREAD

**Issue by asgraf** [FriendsOfCake/crud#488]
### What you did
Inside Model/Entity/User.php
````PHP

	protected $_hidden = [
		'password',
		'api_key'
	];

	protected $_virtual = [
		'display_name'
	];
````
Then requested following urls in the browser:
/users/lookup.json?id=display_name&value=display_name
/users/lookup.json?id=api_key&value=api_key
/users/lookup.json?id=password&value=password

### What happened
Lookup action has not listed display_name virtual column
Lookup action has listed contents of api_key and password columns

### What you expected to happen
List of fields accessible from Lookup action should be configurable via LookupAction config.
Virtual fields should be visible from lookup action unless blacklisted in LookupAction config.
Hidden fields should not be visible from lookup action unless whitelisted in LookupAction config.

**Comment by lorenzo** [comment]
Would you like to submit a PR with this new feature?

**Comment by jippi** [comment]
The code was intended for the developer to use `beforeLookup` event to make sure they get whats expected in the config

**Comment by josegonzalez** [comment]
I like it as is, but agree with @jippi as to it's intended usage (honestly it should just be in the CrudView plugin). We should at the very least add a warning to the docs.

Note: I always force setting the lookup keys in my controller.
