### ISSUE TITLE
Problems with execute Statement

### ISSUE THREAD

**Issue by JulianGerhard** [FriendsOfCake/crud#490]
Dear FoC Team,

I'm very satisfied with your crud-Plugin but I have a question... let's say I have to following add-function:

`        $this->Crud->on('beforeSave', function($user) {
            $user->subject->entity->active = 0;
            $user->subject->entity->walletBalance = 0;
            $user->subject->entity->doubleOptInCode = $this->generateDoubleOptInCode();
        });

        $this->Crud->on('afterSave', function(Event $event) {
            if ($event->subject->created) {
                $this->set('status', 200);
                $this->set('data', [
                    'id' => $event->subject->entity->id,
                    'email' => $event->subject->entity->email,
                    'walletBalance' => $event->subject->entity->walletBalance
                ]);
                $this->set('message', 'Successfully registered user');
                $this->Crud->action()->config('serialize.data', 'data');
                $this->Crud->action()->config('serialize.status', 'status');
                $this->Crud->action()->config('serialize.message', 'message');
            } else {
                $this->set('message', 'Not created');
                $this->Crud->action()->config('serialize.message', 'message');
            }
        });

        return $this->Crud->execute();`

In the success case, everything is alright. If the "else" statement is triggered, I'm receiving the following response:

`{
  "message": "The provided Email-Adress already exists",
  "url": "/users/register",
  "code": 422
}`

To achieve the custom message, I'm currently overwriting your ValidationException __construct method.

My question now is:

How can I achieve a custom response with different keys? The functions in the else-case do not work. I want something like:

`{
  "success": false,
  "message": "<my_custom_message>",
  "code": 422,
 "..."
}`

Thanks in Advance! Great Work!

**Comment by ADmad** [comment]
If you want to change the json response structure you will have to use your own exception render.

**Comment by davidyell** [comment]
I have done this myself in my project recently.

I created a new class in my `/src/Error` folder.

```php
<?php
namespace App\Error;

use Cake\Core\Configure;
use Cake\Core\Exception\Exception as CakeException;
use Cake\Error\Debugger;
use Cake\Error\ExceptionRenderer;
use Cake\Network\Exception\HttpException;

class AppExceptionRenderer extends ExceptionRenderer
{

    public function render()
    {
        //etc
    }
```

You can see that I'm extending the core `ExceptionRenderer` class exactly as @ADmad suggests, and overloading the `render()` method. Which I copied and pasted from the parent class.

To change the output, you'll need to adjust the `viewVars` being passed to the exception. You'll want to look for this part of the `render()` method.

```php
        $viewVars = [
            'message' => $message,
            'url' => h($url),
            'error' => $unwrapped,
            'code' => $code,
            '_serialize' => ['message', 'url', 'code']
        ];
```

In my `AppExceptionRenderer` I changed this to the following, to match my desired error output.

```php
        if ($this->controller->request->is('json') && strpos($this->controller->request->url, "api/v4") !== false) {
            $viewVars = [
                'meta' => [
                    'pagination' => [
                        'page' => null,
                        'next_page' => null,
                        'previous_page' => null,
                        'total_results' => null,
                        'total_pages' => null,
                        'per_page' => null
                    ]
                ],
                'body' => [
                    'results' => null,
                    'error' => [
                        'message' => $message,
                        'url' => $url
                    ]
                ],
                '_serialize' => ['meta', 'body']
            ];
        } else {
            $viewVars = [
                'message' => $message,
                'url' => h($url),
                'error' => $unwrapped,
                'code' => $code,
                '_serialize' => ['message', 'url', 'code']
            ];
        }
```

As you can see, I'm making sure to preserve the existing functionality as well as just changing the error for json.

Lastly you need to tell your application to use your new Exception Renderer, which you can do in the `app.php` file configuration. In the `Error` block of the config, you can just change the renderer used.

```php
    'Error' => [
        'errorLevel' => -1,
        'exceptionRenderer' => \App\Error\AppExceptionRenderer::class,
        'skipLog' => [],
        'log' => true,
        'trace' => true,
    ],
```

Then you're all done.

**Comment by davidyell** [comment]
Oh, don't copy and paste my `-1` error level, that's for development.
