### ISSUE TITLE
Can't change accessible fields in beforeSave

### ISSUE THREAD

**Issue by Drakota** [FriendsOfCake/crud#491]
I'm trying to change the accessible fields beforeSave if the user is a manager

    $this->Crud->on('beforeSave', function(Event $event) {
    	if($this->Auth->user('role') == 'Manager')
    	{
    	    $this->Crud->action()->saveOptions(['accessibleFields' => ['verified' => true]]);
    	}
    });

But it doesn't seems to work, why? I can't change the 'verified' field even though I've changed the saveOptions. I can change every fields I have set to accessible in my entity.php just fine, but when I am trying to change the "verified" field after the beforeSave above, I don't see any change in the object, because it seems to not set the field has accessible.

**Comment by ADmad** [comment]
`accessibleFields` is an option of `Table::patchEntity()` not `Table::save()` and the entity is already patched before `Crud.beforeSave` event is triggered.

So to set `accessibleFields` just do `$this->Crud->action()->config('saveOptions.accessibleFields', ['verified' => true])` in your controller method.
