### ISSUE TITLE
Successful JSON API POST returns Status Code 200 instead of 201

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud#496]
http://jsonapi.org/format/#crud-creating-responses-201

**Comment by bravo-kernel** [comment]
This can be assigned to me, the PR is awaiting integration test.

**Comment by ADmad** [comment]
@bravo-kernel You can assign it to yourself :)

**Comment by bravo-kernel** [comment]
Closing as a PR is now open.
