### ISSUE TITLE
Controller beforeMarshal event not working with beforeSave

### ISSUE THREAD

**Issue by chrisShick** [FriendsOfCake/crud#507]
Changing the data in the beforeMarshal event in the controller does not seem to be making a difference.

    $this->Users->eventManager()->on('Model.beforeMarshal', function(Event $event, \ArrayObject $data, \ArrayObject $options) {
            $data['new_field'] = 'value';
        });

      $this->Crud->on('beforeSave', function (Event $event) {
            $entity = $event->getSubject()->entity;

            var_dump($entity);
            exit();
        });

This dump shows the entity with just the request data.

**Comment by jippi** [comment]
This is because `Crud.beforeSave` is called before `$table->save()`. [see the source](https://github.com/FriendsOfCake/crud/blob/48057dfcf58e26dc27c34b909327d01b1a3fbec4/src/Action/EditAction.php#L121-L124)

So the event chain is `Crud.beforeSave -> table->save() -> Model.beforeMarshal`

**Comment by chrisShick** [comment]
@jippi From the link you provided, it looks like the data is marshaled into the entity before the trigger of the beforeSave???

**Comment by jippi** [comment]
You're right.. though does the subject actually contain the entity ? the code doesn't seem to be adding it

**Comment by jippi** [comment]
is it add or edit you're working with?

**Comment by chrisShick** [comment]
In this case, I am working with add.

**Comment by chrisShick** [comment]
Do I need to add it to the subject? From the examples that I have seen of [beforeMarshal](https://book.cakephp.org/3.0/en/orm/saving-data.html#before-marshal), I shouldn't haven't to add it to the subject.

**Comment by jippi** [comment]
This that case my initial guess was correct? https://github.com/FriendsOfCake/crud/blob/48057dfcf58e26dc27c34b909327d01b1a3fbec4/src/Action/AddAction.php#L111-L127

**Comment by chrisShick** [comment]
@jippi [This](https://github.com/FriendsOfCake/crud/blob/48057dfcf58e26dc27c34b909327d01b1a3fbec4/src/Action/AddAction.php#L114) should be where the marshaling occurs before being set in the entity.

**Comment by chrisShick** [comment]
Alright, so, I have been doing some var dumps in the marshaller and table classes. I basically boiled it down to the fact that in my beforeMarshal event I wanted to replace the $data object with a new one. So, I was doing this: 

      $this->Users->eventManager()->on('Model.beforeMarshal', function(Event $event, \ArrayObject $data, \ArrayObject $options) {
        $new_array = ['new_key' => 'new_value'];
        $data = new \ArrayObject($new_array);
    });

Apparently, this is not the correct way to do it and the original $data object still stayed around instead of being overwritten. To fix the issue I had to do this instead:
 
      $this->Users->eventManager()->on('Model.beforeMarshal', function(Event $event, \ArrayObject $data, \ArrayObject $options) {
        $new_array = ['new_key' => 'new_value'];
        $data->exchangeArray($new_array);
    });
