### ISSUE TITLE
RFC: JSON API Sparse Fieldsets

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud#521]
The JsonApiListener is currently missing [JSON API Sparse Fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets) functionality.

> A client MAY request that an endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] parameter.

```
GET /articles?include=author&fields[articles]=title,body&fields[people]=name HTTP/1.1
Accept: application/vnd.api+json
```

**Comment by ADmad** [comment]
This issue was moved to FriendsOfCake/crud-json-api#1
