### ISSUE TITLE
RFC: JSON API Sorting

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud#522]
The JsonApiListener currently does not fully support [JSON API Sorting](http://jsonapi.org/format/#fetching-sorting) functionality:

- [X] single field sorting (works)
- [ ] multi field sorting (not working)

> A server MAY choose to support requests to sort resource collections according to one or more criteria (“sort fields”).

```
GET /people?sort=age,name HTTP/1.1
Accept: application/vnd.api+json
```

**Comment by bravo-kernel** [comment]
## Single field sorting (works)

Results can be sorted using the `sort` query parameter as can be seen in the following sorted JSON API produced by connecting to `http://cake3api.app/api/cocktails?sort=name`:

```json
{
  "data": [
    {
      "type": "cocktails",
      "id": "8",
      "attributes": {
        "name": "Black Velvet",
        "description": "Beer based",
        "created": "2015-04-11T09:52:02+00:00",
        "modified": null
      },
      "links": {
        "self": "/api/cocktails/8"
      }
    },
    {
      "type": "cocktails",
      "id": "7",
      "attributes": {
        "name": "Bloody Mary",
        "description": "Vodka based",
        "created": "2015-04-11T09:52:02+00:00",
        "modified": null
      },
      "links": {
        "self": "/api/cocktails/7"
      }
    },
    {
      "type": "cocktails",
      "id": "15",
      "attributes": {
        "name": "Boxer",
        "description": "Whiskey based",
        "created": "2015-04-11T09:52:03+00:00",
        "modified": null
      },
      "links": {
        "self": "/api/cocktails/15"
      }
    }
  ]
}
```

### Note

Please note that this requires whitelisting the allowed search fields using `sortWhiteList` in your controller(s):

```php
    public $paginate = [
        'page' => 1,
        'limit' => 3,
        'maxLimit' => 15,
        'sortWhitelist' => [
            'name', 'description'
        ]
    ];
```

**Comment by bravo-kernel** [comment]
To manipulate the direction in which results are sorted use the `direction` parameter. E.g.

```
http://cake3api.app/api/cocktails?sort=name&direction=desc
```

**Comment by dakota** [comment]
Might want to look at implementing a jsonapi middleware eventually to map cakephp pagination and sorting into JSONAPI standard.

**Comment by bravo-kernel** [comment]
## Multiple field sorting (not working)

It seems CakePHP currently does not support sorting on multiple fields. However, things might change. 

- https://github.com/cakephp/cakephp/issues/10028#issuecomment-272812357
- https://github.com/cakephp/cakephp/pull/9791
- https://github.com/cakephp/cakephp/issues/7324

**Comment by dakota** [comment]
Luckily multiple field sorting is optional in the spec :)

**Comment by bravo-kernel** [comment]
Indeed, I should read more carefully ;)

**Comment by ADmad** [comment]
This issue was moved to FriendsOfCake/crud-json-api#2
