### ISSUE TITLE
RFC: JSON API Links

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud#523]
The JsonApiListener is currently missing [JSON API Links](http://jsonapi.org/format/#document-links) functionality.

> Where specified, a links member can be used to represent links. The value of each links member MUST be an object (a “links object”)..

```json
"links": {
  "self": "http://example.com/posts"
}
```

```json
"links": {
  "related": {
    "href": "http://example.com/articles/1/comments",
    "meta": {
      "count": 10
    }
  }
}
```

**Comment by ADmad** [comment]
This issue was moved to FriendsOfCake/crud-json-api#3
