### ISSUE TITLE
RFC: JSON API Filtering (search)

### ISSUE THREAD

**Issue by bravo-kernel** [FriendsOfCake/crud#524]
[JSON API Filtering](http://jsonapi.org/format/#fetching-filtering) should be fully supported using the [FriendsOfCake Search Plugin](https://github.com/FriendsOfCake/search).

> The filter query parameter is reserved for filtering data. Servers and clients **SHOULD** use this key for filtering operations. 

Note: JSON API is **agnostic** about the strategies supported by a server. The filter query parameter can be used as the basis for any number of filtering strategies.

**Comment by bravo-kernel** [comment]
I would prefer if a FoC member would close this issue after verifying but It looks like this is already fully supported by:

- the [SearchListener](https://crud.readthedocs.io/en/latest/listeners/search.html)
- combined with a search alias named `filter` like this:

```php
    public function searchConfiguration()
    {
        $search = new Manager($this);
        $search
            ->like('filter', [
                'before' => true,
                'after' => true,
                'field' => [$this->aliasField('name'), $this->aliasField('description')]
            ]);

        return $search;
    }
```

Connecting to `http://cake3api.app/api/cocktails?filter=beer` filters the results like shown below:

```json
{
  "data": [
    {
      "type": "cocktails",
      "id": "8",
      "attributes": {
        "name": "Black Velvet",
        "description": "Beer based",
        "created": "2015-04-11T09:52:02+00:00",
        "modified": null
      },
      "links": {
        "self": "/api/cocktails/8"
      }
    }
  ]
}
```

**Comment by bravo-kernel** [comment]
**Update:** adding an Ember Data generated URL with filtering which seems to match information about regarding JSON API filtering out there on the internet. Unsure if this can be matched using the Search plugin though.

    /user-profiles?filter[user_id]=1

**Comment by dakota** [comment]
It can if a middleware is written to convert the nested form into a non nested form ☺️

**Comment by ADmad** [comment]
This issue was moved to FriendsOfCake/crud-json-api#4
