### ISSUE TITLE
The "Copy" Action

### ISSUE THREAD

**Issue by DinoSane** [FriendsOfCake/crud#537]
I believe the "Copy" action would be a good improvement. 

It would allows someone to press the copy action button (index page) and then the "action" itself would be to execute the "Add Action"  but with values already filled (copied from that record on grid).

Or a new "Save & Copy" button, witch would save that record, and add a new one with filled fields "waiting" another "Save" to be press.

This expedites creating lot of records that share some fields with repeted values.

**Comment by Spriz** [comment]
Could be done with a listener using https://github.com/riesenia/cakephp-duplicatable at least :)

**Comment by josegonzalez** [comment]
If someone wants to take a crack at implementing this, I do believe it would be a good idea. If not in the core, would be a great CrudAction class to be able to pull in :)
