### ISSUE TITLE
relatedModels: Nested association is not fetched

### ISSUE THREAD

**Issue by LDSign** [FriendsOfCake/crud#543]
Hi

Ive tried to get the data from a nested association to fill out select form fields. "Direct" (1 level deep) associations are working but nothing any deeper.

```php
$this->loadComponent('Crud.Crud', [
	'actions' => [
		'edit' => [
			'className' => 'Crud.Edit',
			'relatedModels' => ['parentCompanies', '**Addresses.States**']
		]
	]
]);

$this->Crud->addListener('relatedModels', 'Crud.RelatedModels');
```

fails with

`Table "App\Model\Table\CompaniesTable" is not associated with "Addresses.States"`

The association is set up correctly and this is working (as well as parentCompanies standalone):

```php
$states = $this->Companies->Addresses->States->find('list');
```

Whats wrong here?

Thanks,
Frank

**Comment by davidyell** [comment]
Have you tried with `'relatedModels' => true` to let Crud traverse the associations?

I assume the configuration you've posted is from your `CompaniesController` ?

**Comment by LDSign** [comment]
Yes, ive tried that too. And yes, the code is in the CompaniesController.

**Comment by ADmad** [comment]
Crud only generates lists for 1st level association. If you need deeper use crud's beforeRender event and set the required lists your self.

**Comment by davidyell** [comment]
We should update the documentation then, as it says this feature exists.

**Comment by LDSign** [comment]
Yes. I thought it will to do this...there is an example in the docs too. So now its clear - Ive to do this on my own...no problem  :)

Any chance to get this in the plugin core? Will save some lines of code... :)

Thanks :)

**Comment by LDSign** [comment]
Hi

Do you have an example of how to return the list of a deeper related model in relatedModel callback?

Can't figure it out :(

Frank

**Comment by davidyell** [comment]
You will find the examples under the Events.

http://crud.readthedocs.io/en/latest/events.html#crud-beforefind
http://crud.readthedocs.io/en/latest/events.html#crud-beforepaginate

**Comment by mehov** [comment]
I had the same issue and googled this up.

The solution was adding `$this->Crud->addListener('relatedModels', 'Crud.RelatedModels')` right after the `$this->loadComponent('Crud.Crud', […])` call.

See #402
