### ISSUE TITLE
Is it possible to use the CRUD API from a plugin?

### ISSUE THREAD

**Issue by jeffreyroberts** [FriendsOfCake/crud#550]
I have my cakephp/app fork which requires crud, and I am making a plugin for that fork which I would like to be able to create an API prefix route with the API controllers in the plugin...

Is this possible? I have the following in my plugin routes.php

    Router::prefix('agents', function ($routes) {
         $routes->extensions(['json', 'xml']);
        $routes->resources('SharpAgent.AgentConfigs');
    });

but I am getting

    Error: Create the class AgentsController below in file: src/Controller/AgentsController.php

Any ideas on how I can get this to work? Is this from a conflicting route in the default app/config/routes.php ?

**Comment by jeffreyroberts** [comment]
And my URL is 

     http://localhost:9001/agents/agent_configs.json

**Comment by ADmad** [comment]
Yes Crud API can be used from a plugin the same way as from app. You have a routing issue, it has nothing to do with Crud plugin. As evident from the error message it's looking for the controller in your app instead of your plugin.
