### ISSUE TITLE
alert-dismissible being ignored by bootstrap-ui

### ISSUE THREAD

**Issue by agarzon** [FriendsOfCake/crud#554]
Hi.

I noticed that _alert-dismissible_ class was not being working in combination wih [friendsofcake/bootstrap-ui](https://github.com/friendsofcake/bootstrap-ui).

According the [doc](http://crud.readthedocs.io/en/latest/events.html#crud-setflash), the code should be like:

```php
$event->getSubject()->params['class'] = 'alert alert-success alert-dismissible';
```

But that doesn't work... then I realized that if I pass the class as an array like:

```php
$event->getSubject()->params['class'] = ['alert', 'alert-success', 'alert-dismissible'];
```

Then it works as should be. 

So I guess is just matter of update the documentation or parse the string into array before passing it as params['class']

**Comment by ADmad** [comment]
Can you please submit a PR updating docs to use  an array?
