### ISSUE TITLE
Using custom ErrorHandler and ErrorRenderer for ApiListener - why is it too late?

### ISSUE THREAD

**Issue by ppisecky** [FriendsOfCake/crud#555]
Hi,

I would like to ask a few things with regards to error handling and I don't know where else to ask.

I am currently working on a project that uses a custom error handler as well as a custom exception renderer for handling exceptions. The error handler is registered within `bootstrap.php` and uses the custom exception renderer explicity:
```php
use App\Error\AppErrorHandler;
$errorHandler = new AppErrorHandler();
$errorHandler->register();
define('DISABLE_DEFAULT_ERROR_HANDLING', 1);
````

For the api portion of the app I want to use Crud, ApiListener and a custom exception renderer that inherits from the Crud one. Because I don't want to break some sort of hidden/implicit functionality I don't want to change the `Error` settings in the `app.php` config which point to the primary custom error renderer. The following call in my main ApiController from which other api controllers inherit of course doesn't work:
```php
$this->Crud->config(['listeners.api.exceptionRenderer' => 'App\Error\Api\ApiExceptionRenderer']);
```

This is due to the following check within the Crud ApiListener:
```php
$appClass = Configure::read('App.namespace') . '\Application';

// If `App\Application` class exists it means Cake 3.3's PSR7 middleware
// implementation is used and it's too late to register new error handler.
if (!class_exists($appClass, false)) {
    $this->registerExceptionHandler();
}
```

I would like to understand the reasoning behind this check. Because doing the following in my ApiController seems to work:
```php
public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Delete',
                'Crud.Edit'
            ]
        ]);

        (new ErrorHandler(['exceptionRenderer' => 'App\Error\Api\ApiExceptionRenderer']))->register();
        $this->Crud->addListener('Crud.Api');
        $this->Crud->addListener('Crud.ApiPagination');
    }
```

**Questions:**
*What is the reasoning for not registering an ErrorHandler within the ApiListener if PSR7 middleware implementation is used?*
*Can something unexpected happen if I register an error handler within my controller the way I did above?*
*How can I use a custom exception renderer without modifying the `app.php` config?*

**Comment by ADmad** [comment]
> I would like to ask a few things with regards to error handling and I don't know where else to ask.

For future reference you can ask on cake's official IRC or slack channel.

> What is the reasoning for not registering an ErrorHandler within the ApiListener if PSR7 middleware implementation is used?

That's because middleware queue cannot be accessed from the ApiListener to setup the custom exception renderer.

> Can something unexpected happen if I register an error handler within my controller the way I did above?

I cannot say what will happen what will happen if you use the framework in unexpected ways. Maybe something bad, maybe nothing.

> How can I use a custom exception renderer without modifying the app.php config?

You need to either do proper config in `app.php` or directly specify required exception render when adding error handler middlware to the middleware queue in `middleware()` method of `src/Application.php`.

**Comment by ADmad** [comment]
> The error handler is registered within bootstrap.php and uses the custom exception renderer explicity:
> 
> use App\Error\AppErrorHandler;
> $errorHandler = new AppErrorHandler();
> $errorHandler->register();
> define('DISABLE_DEFAULT_ERROR_HANDLING', 1);

You aren't supposed to register the error handler yourself. The error handler middleware handles that. You are bound to have problems by doing so.

**Comment by ppisecky** [comment]
Why though? From what I understand the code is based on this example straight from the CakePHP [docs | Error & Exception Handling](https://book.cakephp.org/3.0/en/development/errors.html#creating-your-own-error-handler):

> You can create an error handler out of any callback type. For example you could use a class called AppError to handle your errors. By extending the BaseErrorHandler you can supply custom logic for handling errors. An example would be: 

```php
// In config/bootstrap.php
use App\Error\AppError;

$errorHandler = new AppError();
$errorHandler->register();

// In src/Error/AppError.php
namespace App\Error;

use Cake\Error\BaseErrorHandler;

class AppError extends BaseErrorHandler
{
    public function _displayError($error, $debug)
    {
        echo 'There has been an error!';
    }
    public function _displayException($exception)
    {
        echo 'There has been an exception!';
    }
}
```

**Comment by ADmad** [comment]
That examples predates addition of middleware support to Cake. It works but you don't need to register the handler yourself in bootstrap. Why do you not want to use `app.php` to configure your app to use your custom error handler?

**Comment by ADmad** [comment]
Anyway if you want to use your own error handler do so. Just make it use crud's exception render or your custom exception renderer which extends crud's exception renderer.

**Comment by ppisecky** [comment]
> Why do you not want to use app.php to configure your app to use your custom error handler?

Well going through the docs I didn't find much information about what I am trying to achieve. Most importantly I cannot figure out the relationship between error handlers and the `ErrorHandlerMiddleware`. The problem is that app.php `Error` option allows you to set the `errorRenderer` but not the error handler. About the `ErrorHandlerMiddleware` the docs say:

> Cake\Error\Middleware\ErrorHandlerMiddleware traps exceptions from the wrapped middleware and renders an error page using the [Error & Exception Handling](https://book.cakephp.org/3.0/en/development/errors.html) Exception handler

But looking into the core code of the middleware I cannot find a point where an error handler would be registered, set or even looked up and it seems like the middleware only uses the renderer after all. The only reference to changing the default error handler behavior seems to be my previous example from the docs about which you said it predates the middleware - but the middleware description above points to that part of the documentation. The documentation then also makes a reference to using `set_exception_handler` function but then that seems to be called internally by the `BaseErrorHandler` `register` function.

Right now the main portion of the application seems to be using the custom error handler I mentioned, which gets registered in `bootstrap.php`,  and a custom error renderer called explicitly within the handler but also set in the `app.php` `Error.errorRenderer` option. What I want to achieve is that the API portion of the application use the default error handling behavior and a different custom error renderer. Changint the `app.php` settings might affect the main part of the app. So I opted for registering the handler within base api controller but again I do not understand the relationship between the middleware and the handlers. 

If you have suggestions I will welcome them. But I am going to find the answers on slack as you suggested because this is clearly not your responsibilitty. Thanks a lot :)
