### ISSUE TITLE
Updating association keys while containing related model doesnt update it

### ISSUE THREAD

**Issue by itodor** [FriendsOfCake/crud#558]
Crud fails when you try to update foreign key of entity which is already contained (for example `Offer` entity has shop_id foreign key column and it also contains `Shop` object, so when you try to change `shop_id` value it doesn't get updated because your request data with new shop_id gets overriden with 'original' id of the contained `Shop` object)

**Comment by itodor** [comment]
I actually tested that and its not Cake issue, for example when i run this code:

```
$offersTable = TableRegistry::get('Offers');
        $offer = $offersTable->get(1, ['contain' => ['Shops']]);
        $offer->shop_id = '2'; //originally $offer->shop_id = 1 and shop object is with id = 1
        $offersTable->save($offer);
```

Vanilla cakephp updates the shop_id correctly, but when i use this plugin it gets overriden?

**Comment by ADmad** [comment]
Try using `patchEntity()` to update the foreign key cause that's what Crud uses to update entities before saving.

**Comment by itodor** [comment]
```
$offersTable = TableRegistry::get('Offers');
        $offer = $offersTable->get(136235, ['contain' => ['Shops']]);
        $data = ['shop_id' => 2115];
        $offersTable->patchEntity($offer, $data);
        $offersTable->save($offer);
```

Im using this code and its still working correctly when im not using Crud? Or did you mean something else?

**Comment by ADmad** [comment]
Well if you can confirm that it's a Crud issue a patch is welcome.
