### ISSUE TITLE
ControllerTrait never execute controller action?

### ISSUE THREAD

**Issue by yusser** [FriendsOfCake/crud#562]
Hi,

i was debuging this plugin because my response alwayes return MissingTemplateException. I changed the order. First try component->execute and then controller action. 

```php
        $component = $this->_isActionMapped();
        if ($component) {
            return $component->execute();
        }
        $callable = [$this, $request->params['action']];
        if (is_callable($callable)) {
            return call_user_func_array($callable, $request->params['pass']);
        }
```

Ps: I'm using cakephp 3.5.1 and json extension.

**Comment by ADmad** [comment]
Please provide your action code to reproduce the error.
