### ISSUE TITLE
RFC: Bump minimum Cake version

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#564]
# Outline
I think it is worthwhile to increment the minimum required version of `cakephp/cakephp` for the plugin to take advantage of the newer improvements in the core framework, and also ready the plugin for `4.0`

## Requirements
I propose bumping the minimum to a version above `3.4` so that the getter and setters can be used in the code, and so that the PSR7 classes can be used.

As it's currently `^3.2.2` which is a bit old now.

## Impact
It would require updates to the codebase to remove the deprecations. Updates to the Travis configuration, and also a new major release.

**Comment by ADmad** [comment]
I have already started on this locally :)

**Comment by davidyell** [comment]
Closing in favour of the open Pull Request -> #566
