### ISSUE TITLE
Cannot use class 'object' with PHP 7.2

### ISSUE THREAD

**Issue by ewbarnard** [FriendsOfCake/crud#565]
Fatal error:

` Fatal error: Cannot use Crud\Core\Object as Object because 'Object' is a special class name in ...vendor/friendsofcake/crud/src/Listener/BaseListener.php on line 4`

Reference: [http://php.net/manual/en/reserved.other-reserved-words.php](http://php.net/manual/en/reserved.other-reserved-words.php)

This seems to have hit a number of other libraries as well.
  
Edit: The files to fix are:

* Rename src/Core/Object.php to whatever (I picked FCObject.php, FC being Friends of Cake)
* src/Listener/BaseListener.php 'use' and 'extends' the above
* src/Action/BaseAction.php 'use' and 'extends' the above
* src/Listener/JsonApi/DocumentValidator.php 'use' and 'extends' the above

**Comment by bravo-kernel** [comment]
Are you using a recent version? This seems to have been solved some time ago. https://github.com/FriendsOfCake/crud/pull/548.

**Comment by ewbarnard** [comment]
'composer show | grep -i crud' shows friendsofcake/crud 4.4.4. I'll investigate further.

**Comment by bravo-kernel** [comment]
I think you should upgrade to crud version 5 as this is far from a recent version (if I am reading this right https://packagist.org/packages/friendsofcake/crud)

**Comment by ewbarnard** [comment]
Aha! I was using your tutorial [http://www.bravo-kernel.com/2015/04/how-to-build-a-cakephp-3-rest-api-in-minutes/](http://www.bravo-kernel.com/2015/04/how-to-build-a-cakephp-3-rest-api-in-minutes/) which specifies ~4.0 and not thinking that through. My fault entirely. We can close this issue out. And thank you kindly for the tutorial.

@bravo-kernel What's the best way to contact you with a question related to that tutorial? No need to clutter the issue comments here.

**Comment by bravo-kernel** [comment]
I see, would you mind PR'ing the tutorial so it uses 5 ?

Best way to get support is through the irc/slack channel.

**Comment by ewbarnard** [comment]
I'll get you a PR tonight or tomorrow evening. Thanks!

**Comment by bravo-kernel** [comment]
Awesome, much obliged 👍

**Comment by davidyell** [comment]
Also, worth noting the `composer outdated` command to see which packages are behind the latest release.

**Comment by bravo-kernel** [comment]
Updated the blog to mention `composer require friendsofcake/crud:~5.0`

**Comment by Nishantaryan** [comment]
> 
> 
> I think you should upgrade to crud version 5 as this is far from a recent version (if I am reading this right https://packagist.org/packages/friendsofcake/crud)

It worked i upgraded to Crud 5
