### ISSUE TITLE
View Action Route Problem

### ISSUE THREAD

**Issue by spacebiscuit** [FriendsOfCake/crud#571]
According to the RESTFUL routes in the book:

GET | /recipes.format | RecipesController::index()
GET | /recipes/123.format | RecipesController::view(123)

Using the plugin if i call:

recipes.json the index action is correctly called.

recipes/123.json does not call the view action though, it only works if view is implicitly used:

recipes/view/123.json

If you debug $request->params['action'] of ControllerTrait::index  

The result is '123', this being the action the plugin attempts to call.

**Comment by ADmad** [comment]
Have you actually setup RESTful routes for your controller?

**Comment by spacebiscuit** [comment]
Is that this:


Router::scope('/', function ($routes) {
    // Prior to 3.5.0 use `extensions()`
    $routes->setExtensions(['json']);
    $routes->resources('Recipes');
});
