### ISSUE TITLE
ViewAction and LookupAction is missing api index in $_defaultConfig

### ISSUE THREAD

**Issue by frankvanhest** [FriendsOfCake/crud#572]
From version 5.3 the method `Crud/Listener/ApiListener::respond` is changed to call `$response->withStatus` in stead of `$response->statusCode`. Because the actions View and Lookup don't have the key `api`, the status code in the Response is set to null. CakePHP doesn't check if null is a valid status code and add it to the response. This will result in a 502 bad gateway error in Nginx for example.
There is already a discussion going in cakephp/cakephp (https://github.com/cakephp/cakephp/issues/11677), but it would be advisable to make sure the key `api` exists in the ViewAction and LookupAction.
A pull request will be created shortly.

**Comment by bravo-kernel** [comment]
Much appreciated mr. @frankvanhest. I wonder if this applies to crud-json-api as well.

**Comment by frankvanhest** [comment]
See PR https://github.com/FriendsOfCake/crud/pull/573

**Comment by ADmad** [comment]
Fixed and 5.3.1 released.
