### ISSUE TITLE
How to add additional data to add return data CRUD Api?

### ISSUE THREAD

**Issue by Prasannavk94** [FriendsOfCake/crud#577]
Crud Api add action, returns only the id. I need additional data. How do I do this?

**Comment by raul338** [comment]
See [Serialize](https://crud.readthedocs.io/en/latest/actions/add.html#serialize)

**Comment by Prasannavk94** [comment]
@raul338  Give me a simple example for this.

**Comment by raul338** [comment]
```php
$this->Crud->on('afterSave', function (Event $event) {
    //...
    $this->set([
        'info' => $entity->new_info,
        // ....
    ]);
    $this->Crud->action()->setConfig('serialize', ['info', ....]);
}
```
Thats how you use it (you can call it in any moment, i use it here to get a virtual property after save)

**Comment by Prasannavk94** [comment]
@raul338 Thanks a lot.
