### ISSUE TITLE
How to get Count of Comments with posts as a variable?

### ISSUE THREAD

**Issue by rkaartikeyan** [FriendsOfCake/crud#580]
Hi,

Greetings and thanks in advance. I am new to CakePHP as well as Crud. I have an SQL please help me to achieve it with crud.

```
SELECT posts.*, 
(
    SELECT COUNT(*) 
    FROM comments 
    WHERE comments.post_id = posts.id
) AS totalComments 

FROM posts 
ORDER BY created DESC.
```

**Comment by bravo-kernel** [comment]
This is not a help forum. The ticket tracker is reserved for possible bugs and feature enhancements to the Crud plugin. If you are looking for help on how to implement a feature or to better understand how to use the framework correctly, please visit one of the following:

[The Crud documentation](https://crud.readthedocs.io/en/latest/)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than happy to help answer your questions.

Thanks!
