### ISSUE TITLE
CakePHP 2.10.8 + Crud 3.1.0 + PHP 7.2 = Fatal error

### ISSUE THREAD

**Issue by knnniggett** [FriendsOfCake/crud#581]
CakePHP 2.10.8
Crud 3.1.0
PHP 7.2
Ubuntu 18.04 Beta

Those of us working on the ZoneMinder project have been working towards compatibility with PHP 7.2. 
To accomplish that we are testing the most recent versions of cakphp & crud compatible with our project.

When using CakePHP 2.10.8 and Crud 3.1.0, we see the following fatal error when we make a call to our API, for example: http://localhost/zm/api/host/getVersion.json

```
Fatal error: Uncaught Error: Class 'RelatedModelsListener' not found in /usr/share/zoneminder/www/api/app/Plugin/Crud/Controller/Component/CrudComponent.php:752
Stack trace: 
#0 /usr/share/zoneminder/www/api/app/Plugin/Crud/Controller/Component/CrudComponent.php(728): CrudComponent->_loadListener('RelatedModels') 
#1 /usr/share/zoneminder/www/api/app/Plugin/Crud/Controller/Component/CrudComponent.php(169): CrudComponent->_loadListeners() 
#2 /usr/share/zoneminder/www/api/lib/Cake/Utility/ObjectCollection.php(128): CrudComponent->initialize(Object(CakeErrorController)) 
#3 /usr/share/zoneminder/www/api/lib/Cake/Event/CakeEventManager.php(243): ObjectCollection->trigger('initialize') 
#4 /usr/share/zoneminder/www/api/lib/Cake/Controller/Controller.php(677): CakeEventManager->dispatch(Object(CakeEvent)) 
#5 /usr/share/zoneminder/www/api/lib/Cake/Error/ExceptionRenderer.php(158): Controller->startupProcess() 
#6 /usr/share/zoneminder/www/api/lib/Cake/Error/ExceptionRenderer.php(95): ExceptionRenderer->_getController(Object(FatalErro in /usr/share/zoneminder/www/api/app/Plugin/Crud/Controller/Component/CrudComponent.php on line 752
```

We can fix this fatal error by modifying CrudBaseObject.php
FROM:
`abstract class CrudBaseObject extends Object implements CakeEventListener {`
TO:
`abstract class CrudBaseObject extends CakeObject implements CakeEventListener {`

PR targeting the 3.x branch is incoming...

**Comment by josegonzalez** [comment]
Closed by v3.2.0
