### ISSUE TITLE
How to use ValidationException with current locale

### ISSUE THREAD

**Issue by irongomme** [FriendsOfCake/crud#584]
I'm facing a situation I don't know how to do it. I'm doing a pre-validation, and throw a ValidationException when it does not validate. But I want errors to be translated, and nothing I've tried is currently working in this way ... Does anybody have a clue for doing this ?

```
$user = $this->FrontendUsers->newEntity(
    $this->request->data, 
    ['validate' => 'PreRegistration']
);

if ($user->errors()) {
    throw new ValidationException($user);
}

$this->set([
    'success' => true,
    'data' => $this->request->data,
    '_serialize' => ['success', 'data']
]);
```

**Comment by davidyell** [comment]
I have a vague recollection that you either need to roll your own [ExceptionRenderer class](https://github.com/cakephp/cakephp/blob/master/src/Error/ExceptionRenderer.php#L40-L48). 

However I also have a vague recollection that these error messages are also generated in the translation files, ~~as they're already localised.~~ [No, they are not](https://github.com/cakephp/cakephp/blob/master/src/Core/Exception/Exception.php#L71)

You could always just throw your own exceptions which are localised, and cope with the internationalisation yourself. This would just involve creating your own exceptions, with a wrapped message.

```php
class IronGommeException extends  \Cake\Core\Exception\Exception
{
    public function __construct($message = '', $code = null, $previous = null) {
        parent::__construct($message, $code, $previous);
        $message = __($message);
    }
}
```

[There is more information in the book](https://book.cakephp.org/3.0/en/core-libraries/internationalization-and-localization.html)

**Comment by ADmad** [comment]
`ValidationException` class pull the error message from your entity itself. So you need to translate message in your table.

Closing as there's nothing to be done in Crud plugin here.

**Comment by irongomme** [comment]
Yes you're right, this has nothing to do Crud, I thought validation error messages was implicitely included in i18n extract ... They don't ! So i've wrapped them up with _(), and everything's allright !

Thanks.
