### ISSUE TITLE
bulkDelete should also delete dependent associations

### ISSUE THREAD

**Issue by asgraf** [FriendsOfCake/crud#585]
bulkDelete action ignores 'dependent'=>true option in hasMany associations causing database's constraint violation errors

**Comment by ADmad** [comment]
Bulk delete directly runs delete query on the primary table. We'll probably need an option to do the delete through ORM with callbacks. For now you can use the `Crud.beforeBulk` to delete dependent records first.

You could also just set cascade deletion in dependent tables foreign key constraint in database itself.
