### ISSUE TITLE
 How to create a custom method

### ISSUE THREAD

**Issue by davizxtr** [FriendsOfCake/crud#588]
Hello,
I'm starting to create the api and I started with the bravo kernel tutorial.
It is not clear to me how to make personalized methods. For example, a method to obtain adverts filtering by tag, by category ... that is paged ... etc

I have tried the following.
I do not know if it is the most appropriate.

It would help me a lot an example of a complete api with cakephp.

![image](https://user-images.githubusercontent.com/37248385/38829488-7c9c73ac-41b9-11e8-9ab8-6a00325fa2f7.png)

A greeting.
Thank you very much

David.

**Comment by ADmad** [comment]
This is an issues tracker not a help forum. Please use one of the official CakePHP help forums/channels.
