### ISSUE TITLE
CakePHP 3.6 support

### ISSUE THREAD

**Issue by mfrascati** [FriendsOfCake/crud#591]
Since Cake 3.6 fires deprecation warnings on functions and namespaces, have you thinked about a release supporting this version? Should it be a new branch to not break backwards compatibility?

(I know I can hide the warnings, but it's better to enhance support rather than hiding dust under the carpet!)

**Comment by ADmad** [comment]
Which version are you using? The latest 5.4.1 release shouldn't show any notices with cake 3.6.

**Comment by mfrascati** [comment]
I'm using latest version 5.4.1

Calling a view for a missing record fires the deprecated Network\Exception

`
Notice: Deprecated (16384): Use Cake\Http\Exception\NotFoundException instead of Cake\Network\Exception\NotFoundException. - /var/www/html/back-end/vendor/composer/ClassLoader.php, line: 444
...
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE/src/Error/BaseErrorHandler.php, line 153
deprecationWarning - CORE/src/Core/functions.php, line 307
include - CORE/src/Network/Exception/NotFoundException.php, line 4
Composer\Autoload\includeFile - ROOT/vendor/composer/ClassLoader.php, line 444
Composer\Autoload\ClassLoader::loadClass() - ROOT/vendor/composer/ClassLoader.php, line 322
spl_autoload_call - [internal], line ??
Crud\Action\ViewAction::_notFound() - ROOT/vendor/friendsofcake/crud/src/Traits/FindMethodTrait.php, line 95
Crud\Action\ViewAction::_findRecord() - ROOT/vendor/friendsofcake/crud/src/Traits/FindMethodTrait.php, line 71
Crud\Action\ViewAction::_handle() - ROOT/vendor/friendsofcake/crud/src/Action/ViewAction.php, line 53
Crud\Action\BaseAction::handle() - ROOT/vendor/friendsofcake/crud/src/Action/BaseAction.php, line 71
Crud\Controller\Component\CrudComponent::execute() - ROOT/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php, line 241
App\Controller\AppController::view() - ROOT/vendor/mfrascati/utils/src/Lib/CrudBasicTrait.php, line 40
App\Controller\AppController::invokeAction() - ROOT/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php, line 63
...
`

So far this is the only case I found

**Comment by bravo-kernel** [comment]
Same here @ADmad while running a new crud-json-api IntegrationTest. 

- `NotFoundException` does not exist within the crud-json-api code
- composer version for cakephp: * 3.6.3
- composer version for crud: * 5.4.1

The integration test:

```php
<?php
namespace CrudJsonApi\Test\TestCase\Integration\JsonApi;

use CrudJsonApi\Test\TestCase\Integration\JsonApiBaseTestCase;

class ErrorsIntegrationTest extends JsonApiBaseTestCase
{
    /**
     * Make sure 404 is properly handled for Resources
     */
    public function test404ForResources() {
        $this->get('/countries/666');
        $this->assertResponseCode(400);
        $this->_assertJsonApiResponseHeaders();
        $this->assertResponseEquals($this->_getExpected('Errors' . DS . 'validation-error.json'));
    }
}
```


Stacktrace:

```
1) CrudJsonApi\Test\TestCase\Integration\JsonApi\ErrorsIntegrationTest::test404ForResources
Use Cake\Http\Exception\NotFoundException instead of Cake\Network\Exception\NotFoundException. - /home/vagrant/projects/crud-json-api/vendor/composer/ClassLoader.php, line: 444
 You can disable deprecation warnings by setting `Error.errorLevel` to `E_ALL & ~E_USER_DEPRECATED` in your config/app.php.

/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Core/functions.php:312
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Network/Exception/NotFoundException.php:4
/home/vagrant/projects/crud-json-api/vendor/friendsofcake/crud/src/Traits/FindMethodTrait.php:95
/home/vagrant/projects/crud-json-api/vendor/friendsofcake/crud/src/Traits/FindMethodTrait.php:71
/home/vagrant/projects/crud-json-api/vendor/friendsofcake/crud/src/Action/ViewAction.php:53
/home/vagrant/projects/crud-json-api/vendor/friendsofcake/crud/src/Action/BaseAction.php:71
/home/vagrant/projects/crud-json-api/vendor/friendsofcake/crud/src/Controller/Component/CrudComponent.php:241
/home/vagrant/projects/crud-json-api/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php:68
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php:120
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php:94
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Http/BaseApplication.php:228
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Http/Runner.php:65
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php:158
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Http/Runner.php:65
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php:88
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Http/Runner.php:65
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Http/Runner.php:51
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/Http/Server.php:98
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php:97
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php:493
/home/vagrant/projects/crud-json-api/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestCase.php:375
/home/vagrant/projects/crud-json-api/tests/TestCase/Integration/JsonApi/ErrorsIntegrationTest.php:12
```

**Comment by bravo-kernel** [comment]
I cn confirm this resolves the issue. Thank you for the quick action!
