### ISSUE TITLE
XML POST Request: validation errors

### ISSUE THREAD

**Issue by smap9** [FriendsOfCake/crud#594]
## What I did

I want to create a RESTful API to transfer data with XML.

I created a route like this:
```php
Router::prefix('api', function ($routes) {
    $routes->extensions(['json', 'xml']);
    $routes->resources('Employees');
});
```
My Controller looks like
```php
namespace App\Controller\Api;

class EmployeesController extends \Cake\Controller\Controller
{
    use \Crud\Controller\ControllerTrait;

    public function initialize()
    {
        $this->loadComponent('RequestHandler', [
            'enableBeforeRedirect' => false
        ]);

        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'Crud.Api',
                'Crud.ApiPagination',
                'Crud.ApiQueryLog'
            ]
        ]);
    }
}
```

I send a request with header ```Content-Type: application/xml``` and content
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<request>
     <department>IT</department>
     <active>true</active>
     <name>Stephan</name>
     <surname>Meyer</surname>
</request>
```
## What happens

The response contains the error message ```4 validation errors occurred```

## What I expect to happen

the entity should be saved

## Debugging

I debugged for some time and if I add ```debug($this->_request()->getData());exit;``` to https://github.com/FriendsOfCake/crud/blob/fb272d3b0fbd806162699ce353fb253f7c1a63b5/src/Action/AddAction.php#L113 the output is
```
[
	'request' => [
		'department' => 'IT',
		'active' => 'true',
		'name' => 'Stephan',
		'surname' => 'Meyer'
	]
]
```
This is equal to the XML but to patch the entity I need some format like
```
[
	'department' => 'IT',
	'active' => 'true',
	'name' => 'Stephan',
	'surname' => 'Meyer'

]
```
This behavior comes from the default CakePHP ```inputTypeMap``` of RequestHandler.

Sending the data with JSON (header ```application/json```) works as expected.

**Comment by smap9** [comment]
Without the wrapping ```<request>``` the XML is not parsed. RequestHandlerComponent is parsing the XML in https://github.com/cakephp/cakephp/blob/a6fa3656aa4f62d641f6a31e513472efe1b52e8c/src/Controller/Component/RequestHandlerComponent.php#L236

I tested it in two scripts

### first
```php
        $xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<department>IT</department>
<active>true</active>
<name>Stephan</name>
<surname>Meyer</surname>';
        try {
            $xml = Xml::build($xml, ['return' => 'domdocument', 'readFile' => false]);
            // We might not get child nodes if there are nested inline entities.
            if ($xml->childNodes->length > 0) {
                debug(Xml::toArray($xml));exit;
            }
            debug('no child nodes');exit;
        } catch (XmlException $e) {
            debug($e);exit;
        }
```
Displays ```'no child nodes'```

### second

```php
        $xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<request>
    <department>IT</department>
    <active>true</active>
    <name>Stephan</name>
    <surname>Meyer</surname>
</request>';
        try {
            $xml = Xml::build($xml, ['return' => 'domdocument', 'readFile' => false]);
            // We might not get child nodes if there are nested inline entities.
            if ($xml->childNodes->length > 0) {
                debug(Xml::toArray($xml));exit;
            }
            debug('no child nodes');exit;
        } catch (XmlException $e) {
            debug($e);exit;
        }
```
displays
```
[
	'request' => [
		'department' => 'IT',
		'active' => 'true',
		'name' => 'Stephan',
		'surname' => 'Meyer'
	]
]
```

**Comment by ADmad** [comment]
Hmm.. This might be as a result of cake 2.x days where the form data was expected to nested under `data` key, hence the requirement for needed a outer wrapping tag like this test case shows.

https://github.com/cakephp/cakephp/blob/a6fa3656aa4f62d641f6a31e513472efe1b52e8c/tests/TestCase/Controller/Component/RequestHandlerComponentTest.php#L644

This is an issue with core's RequestHandlerComponent not Crud.

**Comment by smap9** [comment]
A XML-Document must have a root-tag to be valid: https://www.w3schools.com/xml/xml_syntax.asp

so to my mind the second example shold be the valid request and CRUD shold remove the root tag from the request data

**Comment by ADmad** [comment]
Populating request data from XML input is not Crud's job. That's done by the RequestHandlerComponent. So please open an issue on CakePHP core.

**Comment by smap9** [comment]
@ADmad i do not agree this is a mistake of RequestHandlerComponent. The Component is its job. I think one is not able to  send a valid XML to CRUD that can be stored as a new entity, because to send a valid XML you have to use a root tag. But if you use a root tag you get a root element in the populated request data. To my mind the root array has to be removed by CRUD. If the behavior of the RequestHandlerComponent will be changed it would be a breaking change because all the tests in https://github.com/cakephp/cakephp/blob/a6fa3656aa4f62d641f6a31e513472efe1b52e8c/tests/TestCase/Controller/Component/RequestHandlerComponentTest.php#L644 using ```domdocument``` will fail.
