### ISSUE TITLE
Group by

### ISSUE THREAD

**Issue by thiagoreri** [FriendsOfCake/crud#605]
Is possible use groupby in index action?

**Comment by thiagoreri** [comment]
is only returning 1 record

**Comment by ADmad** [comment]
Crud doesn't how the ORM works in anyway. Your issue is unrelated to this plugin.

**Comment by davidyell** [comment]
You would need to do that code yourself, by using the event hooks.

```php
$this->Crud->on('beforePaginate', function (\Cake\Event\Event $event) {
    $event->getSubject()->query->group();
};
```

More details in the documentation https://crud.readthedocs.io/en/latest/events.html#crud-beforepaginate
