### ISSUE TITLE
RFC: Enhance Subject class properties

### ISSUE THREAD

**Issue by davidyell** [FriendsOfCake/crud#607]
Following on from #185 PHP Stan gets upset because many of the properties being accessed from the event subject do not exist in the class.

Some examples are
`$event->getSubject()->query` 👉 `Access to an undefined property object::$query.`
`$event->getSubject()->url` 👉 `Access to an undefined property object::$url.`
`$event->getSubject()->association` 👉 `Access to an undefined property object::$association.`

I am not too sure on the approach to solving this, as I expressed a while back in #394 but perhaps it needs a magic method here? Or at least some nullable properties adding to the class perhaps?

As it's a wrapping class there might be lots of properties. I have not been through all the contextual uses of the event subject to see which properties might be viable. The above examples are just from my project.

I have currently sidestepped the issue by ignoring the problem in phpstan.
```neon
    ignoreErrors:
        - '#Access to an undefined property object::\$[\w]+\.#'
```

**Comment by ADmad** [comment]
The `Subject` class is [universal object crate](https://github.com/phpstan/phpstan#universal-object-crates). So the only improvement would be using phpstan's `universalObjectCratesClasses` parameter instead of `ignoreErrors`.

**Comment by ADmad** [comment]
The plugin's `phpstan.neon` already has `Subject` under `universalObjectCratesClasses` so I don't think there's anything to be done here.
