### ISSUE TITLE
Missing template

### ISSUE THREAD

**Issue by dasca** [FriendsOfCake/crud#610]
When using CakePHP 3.7.5 and following the Installation and Quick Start sections of the crud documentation with in it self needs some updating due to deprecated methods i.e:

> Loading the plugin
> Add the following to your /config/bootstrap.php
> 
> Plugin::load('Crud'); 

You don't get the expected results when doing GET request on actions and accepting application/json result.

I always end up with template file missing such as:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/2222967/54870615-3a092380-4da9-11e9-85b1-8dfe90425674.png">

**Comment by davidyell** [comment]
The plugin only requires 3.5 at the moment. Once the minimum framework version is pushed to 3.7 then the documentation can be updated.

I wonder if you have the RequestHandler setup correctly, as you should not need a template for a JSON request.

**Comment by ADmad** [comment]
Use the application class to load plugin if you are using new cakephp version. How the plugin is loaded has nothing to do with your particular issue. Ensure you have loaded `RequestHandler` and setup `ApiListener` properly.
