### ISSUE TITLE
Undefined property: Crud\Event\Subject::$id

### ISSUE THREAD

**Issue by waspinator** [FriendsOfCake/crud#615]
I'm saving an new entity with associations, and I can see the newly created id in the `_joinData` field, but the base entity does not have an `id` field, and neither does `_subject`, even though `success => true` and `created => true`.

Any ideas how those conditions can coexist?

```
public function add()
{
    $this->Crud->on('afterSave', function(\Cake\Event\Event $event) {
        if ($event->getSubject()->created) {
            $this->log("The entity was created with id: " . $event->getSubject()->id);
        }
    });

    return $this->Crud->execute();
}
```

https://crud.readthedocs.io/en/latest/events.html#get-entity-id

**Comment by davidyell** [comment]
I think this might be an error in the documentation? Did you try `$event->getSubject()->entity->id` ?

**Comment by ADmad** [comment]
Yup it's a documentation error. A fix to the docs is welcome.

**Comment by waspinator** [comment]
how often are the docs re-built?

**Comment by ADmad** [comment]
After each commit, but the readthedocs hook was broken :slightly_smiling_face:. It's fixed now and docs updated.
