### ISSUE TITLE
API Prefix Calls Index in Error

### ISSUE THREAD

**Issue by spacebiscuit** [FriendsOfCake/crud#617]
I have followed the CRUD Api guide to setup for API prefix routing with the plugin:

Routes.php:

```
Router::prefix('Api', function ($routes) {
    $routes->extensions(['json', 'xml', 'ajax']);
    $routes->fallbacks('InflectedRoute');
});
```

```
namespace App\Controller\Api;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\Core\Exception\Exception;

class ApiAppController extends AppController {

    use \Crud\Controller\ControllerTrait;

    public function initialize() {

        $this->loadComponent('Crud.Crud'); 

        $this->Crud->addListener('Crud.Api');
        $this->Crud->addListener('Crud.ApiPagination');
        $this->Crud->addListener('relatedModels', 'Crud.RelatedModels');
    }
}
```

My controller:

```
namespace App\Controller\Api;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\Utility\Security;
use Cake\Mailer\Email;
use Cake\Utility\Hash;
use Cake\Network\Http\Client;
use Cake\ORM\TableRegistry;
use App\Http\Exception\CustomException;
use \DateTime;

class MessagesController extends ApiAppController {

    public function initialize() {  
        parent::initialize();      
    }

    public function beforeFilter(Event $event){

        parent::beforeFilter($event);      
        $this->Crud->mapAction('add', 'Crud.Add');
        $this->Crud->mapAction('update', 'Crud.Edit');
    }

    public function add() {      
        return $this->Crud->execute();
    }

 }
```
When I call POST /api/messages.json

Action MessagesController::index() could not be found, or is not accessible.

I don't have an index controller and I am not calling index controller. This seems to be a bug because if I remove the api prefix the call works.

**Comment by ADmad** [comment]
You haven't mapped any [actions](https://crud.readthedocs.io/en/latest/configuration.html#actions) when loading the Crud component, hence the error.

**Comment by spacebiscuit** [comment]
Thanks add the mapped resource worked for the Messages controller but consider the following:


```
Router::prefix('Api', function ($routes) {
    $routes->extensions(['json', 'xml', 'ajax']);
    $routes->resources('ReportedListings');
    $routes->resources('Messages');    
});
```

My url is /api/reported-listings.json {POST]

Error: Action ReportedListingsController::index() could not be found, or is not accessible.

If I add an index function to the controller no error is thrown. It seems there is a problem if the controller is two words?

**Comment by ADmad** [comment]
Read the API docs for [RouteBuilder::resources()](https://api.cakephp.org/3.7/class-Cake.Routing.RouteBuilder.html#_resources) method and you will have your answer. :slightly_smiling_face:.

In future please use one of CakePHP's help forum first to ensure whether a problem you are having is actually due to a bug or just implementation issue on your part.

**Comment by spacebiscuit** [comment]
Thanks - I've read that but it doesn't solve the issue. See my routes.php:

https://gist.github.com/spacebiscuit/5b9f07215523728cf65dad631ae17c88

Trying the following:

api/reported-listings.json
api/reported_listings.json
api/reportedListings.json

All give the same result. This would suggest to me that the Plugin doesn't work with multi-word controllers.

**Comment by spacebiscuit** [comment]
The solution was to maker the 'Api' lowercase:

```
Router::prefix('api', function ($routes) {
    $routes->extensions(['json', 'xml', 'ajax']);    
    $routes->resources('ReportedListings');
    $routes->resources('Messages');
    $routes->fallbacks(DashedRoute::class);
});
```

For some reason with an uppercase 'Api' the restful routing doesn't work correctly with multi-word controlers.
