### ISSUE TITLE
set id on view action if not set?

### ISSUE THREAD

**Issue by waspinator** [FriendsOfCake/crud#625]
How would you set the `/view/$id` variable if it wasn't supplied in the url?

The code below adds another condition (`:c1`) instead of replacing the original one (`:c0`).

`FROM users Users WHERE (Users.id = :c0 AND id = :c1)` 

```php
    public function view()
    {
        $this->Crud->on('beforeFind', function(Event $event) {
            if ($event->getSubject()->id == null) {
                $id = $this->Authentication->getIdentity()->id;
                $event->getSubject()->query->where(['Users.id' => $id]);
            }
        });

        return $this->Crud->execute();
    }
```

**Comment by raul338** [comment]
See the second parameter of [execute](https://github.com/FriendsOfCake/crud/blob/master/src/Controller/Component/CrudComponent.php#L226), example
```php
$this->Crud->execute(null, [
    $this->request->getData('id')
]);
```
