### ISSUE TITLE
How to handle CORS (e.g. DELETE)?

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud#626]
I'm trying to get DELETE to work via axios. It works from Postman but not from axios in any browser. I'm running up against pre-flight check OPTIONS. There's no mention of CORS in the crud documentation and looking at what's available in the CakePHP manual it looks like one would have to set it per action, which doesn't really gel with the crud plugin. 

I assume someone has got this to work and that this isn't actually a bug but it would be great if you could let me know how or modify the docs so that they do.

**Comment by ADmad** [comment]
The Crud plugin has nothing to do with setting CORS headers and that's why there's no mention of it in docs.

Please use one of CakePHP's help forum for support.
