### ISSUE TITLE
Face issue in API (Could not find listener class)

### ISSUE THREAD

**Issue by mss-mohdali** [FriendsOfCake/crud#627]
> 

![Screenshot from 2019 09 06 17 43 55 png  PNG Image  1366 × 768 pixels    Scaled  83  ](https://user-images.githubusercontent.com/19199710/64427251-63efa180-d0ce-11e9-9a20-8ec43a3a2956.png)

**Comment by davidyell** [comment]
Not really much to go on here. What listener are you expecting to be loaded? What does your Crud configuration look like?

**Comment by Phally** [comment]
Closing this. Old issue and indeed needs more info.

Probably a configuration issue if I had to guess.
