### ISSUE TITLE
CakePHP 4.x Compatibility update

### ISSUE THREAD

**Issue by chcnetconsulting** [FriendsOfCake/crud#633]
Hi
I am already using cakephp 4.x and would like to use your crud plugin, but composer refuses installation :-(((

  Problem 1
    - friendsofcake/crud 5.4.0 requires cakephp/cakephp ^3.5 -> satisfiable by cakephp/cakephp[3.x-dev].
    - friendsofcake/crud 5.4.1 requires cakephp/cakephp ^3.5 -> satisfiable by cakephp/cakephp[3.x-dev].
    - friendsofcake/crud 5.4.2 requires cakephp/cakephp ^3.5 -> satisfiable by cakephp/cakephp[3.x-dev].
    - friendsofcake/crud 5.4.3 requires cakephp/cakephp ^3.5 -> satisfiable by cakephp/cakephp[3.x-dev].
    - friendsofcake/crud 5.4.4 requires cakephp/cakephp ^3.5 -> satisfiable by cakephp/cakephp[3.x-dev].
    - friendsofcake/crud 5.4.5 requires cakephp/cakephp ^3.5 -> satisfiable by cakephp/cakephp[3.x-dev].
    - friendsofcake/crud 5.4.6 requires cakephp/cakephp ^3.5 -> satisfiable by cakephp/cakephp[3.x-dev].
    - friendsofcake/crud 5.4.7 requires cakephp/cakephp ^3.5 -> satisfiable by cakephp/cakephp[3.x-dev].
    - Conclusion: don't install cakephp/cakephp 3.x-dev
    - Installation request for friendsofcake/crud ^5.4 -> satisfiable by friendsofcake/crud[5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.4.5, 5.4.6, 5.4.7].

**Comment by dakota** [comment]
You need to install Crud version 6.0.0-beta (`composer require friendsofcake/crud:^6.0.0-beta`)

**Comment by chcnetconsulting** [comment]
Hi, unfortunately I cannot find the required version:

% composer require friendsofcake/crud:^6.0.0-beta                           
zsh: no matches found: friendsofcake/crud:^6.0.0-beta
christoph@Christophs-Mac-mini msjbe % 



Mit freundlichen Grüßen

CHCNET Hosting & Coding
Christoph Christ
Wienerstrasse 23
A.2410 Hainburg/Donau

Tel: +43-2165-93059
Fax: +43-2165-93059 - 339
Mobil: +43-664-2382384

UID-Nr: ATU61214947
email: office@chcnet.at

> Am 20.01.2020 um 08:26 schrieb Walther Lalk <notifications@github.com>:
> 
> composer require friendsofcake/crud:^6.0.0-beta

**Comment by dakota** [comment]
That might be something with zsh. How do you normally run composer?

**Comment by chcnetconsulting** [comment]
It’s not zsh’s fault.


I found out, that I had to replace ^ with ~ to get the plugin from repository…. Now it’s installed *yikes*


% composer require friendsofcake/crud:~6.0.0-beta
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing friendsofcake/crud (6.0.0-beta): Downloading (100%)         
friendsofcake/crud suggests installing friendsofcake/search (Provides search capabilities for the Crud plugin.)
friendsofcake/crud suggests installing friendsofcake/crud-view (Automated admin backend based on your Crud configuration.)
friendsofcake/crud suggests installing friendsofcake/crud-json-api (Crud listener for building APIs following the JSON API specification)
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
Package zendframework/zend-httphandlerrunner is abandoned, you should avoid using it. Use laminas/laminas-httphandlerrunner instead.
Writing lock file
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump



Mit freundlichen Grüßen

CHCNET Hosting & Coding
Christoph Christ
Wienerstrasse 23
A.2410 Hainburg/Donau

Tel: +43-2165-93059
Fax: +43-2165-93059 - 339
Mobil: +43-664-2382384

UID-Nr: ATU61214947
email: office@chcnet.at
