### ISSUE TITLE
4.x) Crud.ApiPagination doesn't add "pagination" to response.

### ISSUE THREAD

**Issue by bebna** [FriendsOfCake/crud#634]
Following line:

https://github.com/FriendsOfCake/crud/blob/0199520026ca5aa38e2b894da8829dbea88dc886/src/Listener/ApiPaginationListener.php#L44
doesn't find anything even when pagination is active from CakePHP 4.

This is because data it looks for is in the attributes, see:

https://github.com/FriendsOfCake/crud/blob/0199520026ca5aa38e2b894da8829dbea88dc886/src/Action/IndexAction.php#L64

Which results in that no ``pagination`` field is added with pagination metadata to the serialized response.

**Comment by ADmad** [comment]
You have opened the pull request for the fix against your own fork instead of this repo :)

**Comment by bebna** [comment]
Yeah, ignore that. I became too sleepy, after trying to debug something in the front end for hours till almost midnight, to really follow githubs website anymore. There was some message about no writing rights and it would copy the change to my fork to create a pull request. And the pull request didn't tell me itself if it is targeting my fork or not. After which I found #629, so there wasn't even a reason anymore to keep that fork anyway and started to go home and left it.

Anyway,...

Please mark this belonging to #629 and merge that pull request, mine doesn't contain the unit test changes.

Also please merge #629 as soon as possible, thanks.

**Comment by ADmad** [comment]
Fixed in #629
