### ISSUE TITLE
POST Request getData() is empty

### ISSUE THREAD

**Issue by hitesh-shah** [FriendsOfCake/crud#635]
https://github.com/FriendsOfCake/crud/blob/19c4b9053b0e90871b87110c5bf287704087a351/src/Action/AddAction.php#L120

https://book.cakephp.org/4/en/controllers/request-response.html
// Get JSON encoded data submitted to a PUT/POST action
$jsonData = $this->request->input('json_decode');

// Get XML encoded data submitted to a PUT/POST action
$data = $this->request->input('Cake\Utility\Xml::build', ['return' => 'domdocument']);

//Below code works for me when Content-Type is application/json
$data = $this->_request()->input('json_decode',true);

//Below code works for me when Content-Type is application/xml
$xml = $this->_request()->input('Cake\Utility\Xml::build');
$array = \Cake\Utility\Xml::toArray($xml);
foreach ($array as $value) {
 $data = $value;
}

**Comment by Phally** [comment]
This is not a feature of the CRUD plugin as it's already in CakePHP. The manual states you have to add the `RequestHandler` component:

> Lastly, if XML/JSON data is POST’ed to your Controllers, it will be parsed into an array which is assigned to $this->request->getData(), and can then be accessed as you would standard POST data. In order to make use of RequestHandler it must be included in your `initialize()` method:

See: https://book.cakephp.org/4/en/controllers/components/request-handling.html
