### ISSUE TITLE
Event beforeMarshal for modifying data before patching

### ISSUE THREAD

**Issue by blieb** [FriendsOfCake/crud#650]
Hi,

I need to modify some incoming data before the entity is patched, I want to do this in a listener. But I don't see a way to change data in a listener before it is patched. 

At the moment I do this in a beforeSave, but this gives problem with validation when you do a requirePresence validation. it tells that field is required while there is data in it. this because it runs the validation only with the new incoming data. 

so it is better to change the data before patching it. but there is no callback for that. is it maybe a good idea to implement a beforeMarshal callback in the crud events?  

I only need to know the data, and the entity or table that is used for patching. :)

**Comment by ADmad** [comment]
Validation is for incoming request data. Since you are setting data yourself either directly set entity property or turn off validation when patching entity.

I don't see the need for Crud to duplicate every model event when simple alternatives to your problem exist.

**Comment by ADmad** [comment]
Also you can use "fieldList" option of patchEntity() only for fields you are passing.

**Comment by blieb** [comment]
I think this is a missing feature, at the moment it is not possible to modify data before patching (at least in a listener). I think this is a better idea than do it before save.

Also giving the fieldList is a good solution too. Better than skipping the validation, tnx! 👍
