### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by adoniahei** [FriendsOfCake/crud#652]
Attempting to install CRUD in a fresh install of Linux Mint 20, I got the following errors:

dlc@business:~/UnclaimedProperty/CRUD$ composer require friendsofcake/crud
Using version ^6.0 for friendsofcake/crud
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 15 installs, 0 updates, 0 removals
  - Installing psr/simple-cache (1.0.1): Downloading (100%)         
    Failed to download psr/simple-cache from dist: Could not delete ~/UnclaimedProperty/CRUD/vendor/psr/simple-cache/.editorconfig: 
    Now trying to download from source
  - Installing psr/simple-cache (1.0.1): 
Installation failed, deleting ./composer.json.

In Filesystem.php line 217:
                                                                                                                                
  Could not delete ~/UnclaimedProperty/CRUD/vendor/psr/simple-cache/.editorconfig:  
                                                                                                                                

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>...]

**Comment by ADmad** [comment]
You seem to be having some network issues and/or file permissions issues. Delete your `vendor` folder and try again.
