### ISSUE TITLE
Hiding Properties defined in $_hidden in the model Entity does not work [2]

### ISSUE THREAD

**Issue by mehov** [FriendsOfCake/crud#659]
Following the [documentation on hiding Entity fields](https://book.cakephp.org/3/en/orm/entities.html#hiding-fields), in my `App/Model/Entity/User.php` I have:

```
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

class User extends Entity
{

    protected $_hidden = [
        'password',
        'salt',
    ];

}
```

When I use [FriendsOfCake/crud](https://github.com/FriendsOfCake/crud) to render the index page, in the resulting table I still see those values I had listed under `$_hidden`. I found a similar issue #308 from 6 years ago, where pretty much right away the author [comes back saying](https://github.com/FriendsOfCake/crud/issues/308#issuecomment-124453470) *You just have to remember to load your model* which I'm not sure what that means.

Either way, to confirm my Model/UsersTable class picks up the right entity, and that the entity is configured correctly, I did a quick test in an arbitrary controller:

1. `debug($this->Users->find('all')->first()`: displays the hidden fields
2. `debug($this->Users->find('all')->first()->toArray())`: doesn't display the hidden fields (which according to [this comment](https://stackoverflow.com/questions/40226293/hidden-fields-are-still-listed-from-database-in-cakephp-3#comment68824746_40239674) is the expected behaviour)

So how do I have [FriendsOfCake/crud](https://github.com/FriendsOfCake/crud) follow my Entity configuration, and should it be doing that in the first place? Or am I missing something?

**Comment by mehov** [comment]
I can see [it's possible](https://crud-view.readthedocs.io/en/latest/customizing-templates.html#removing-fields-from-output) to remove certain fields from the output using `scaffold.fields_blacklist`, but that seems against the *DRY* and *convention over configuration* principles seeing that I already have exactly that specified in the corresponding Entity.

**Comment by ADmad** [comment]
As the Cake manual states $_hidden property of entity only controls hiding of fields when the entity is JSON encoded or converted to array, neither of which is done when generating the index page.

You can add your own listener for the `Crud.before beforePaginate` event to populate `scaffold.fields_blacklist` option based on entity's hidden fields.

**Comment by mehov** [comment]
Thank you for the tip. Here's how I did it:

```
public function initialize()
{
    parent::initialize();

    $this->viewClass = 'CrudView\View\CrudView';
    $this->loadComponent('Crud.Crud', [
        // …
    ]);
    $this->Crud->on('beforePaginate', function(\Cake\Event\Event $event) {
        $newEntity = $event->getSubject()->query->getRepository()->newEntity();
        $this->Crud->action()->setConfig(
            'scaffold.fields_blacklist', $newEntity->getHidden()
        );
    });

}
```

Is this the right way to do this? My concerns are:

- CakePHP transitioned to explicit get/set methods, but `$event->getSubject()->getQuery()` is undefined, so had to use `$event->getSubject()->query` property instead
- Same with undefined `$this->Crud->getAction()->setConfig()`, had to call `$this->Crud->action()`
- I'm not sure if `$event->getSubject()->getQuery()->getRepository()->newEntity()` is the most effective way to get an Entity instance, but doing `$event->getSubject()->getQuery()->first()` could be even worse if that would have unnecessarily ran the query one extra time

Please let me know. Thank you!
