### ISSUE TITLE
The `description` column won't save; `title` works though

### ISSUE THREAD

**Issue by mehov** [FriendsOfCake/crud#667]
I'm editing an item that has a title and a description. When I type a new description and hit save, no changes are written to the database. However, updating the title does work. Lastly, changing the description directly in the database using MySQL Workbench works, and the CRUD plugin shows the updates immediately.

Using the latest CakePHP, CRUD and CRUD-View plugins.

I would love to provide more information, but not sure what to debug. Please let me know where to look

**Comment by davidyell** [comment]
This sounds like a missing `$_accessible` in the Entity to me. You can find out more about entity mass assignment attack protection in the book 

https://book.cakephp.org/4/en/orm/entities.html#mass-assignment

**Comment by mehov** [comment]
@davidyell thank you for the tip, now that you've pointed that out, I indeed remember I didn't have the `description` column when I was baking the models, I added the column only later, but never updated the corresponding Entity code. I will get back here after I add it to `$_accessible` and confirm, but I'm already pretty sure you got it right.
