### ISSUE TITLE
Adding WHERE condition to the index action

### ISSUE THREAD

**Issue by VARGA-Peter** [FriendsOfCake/crud#671]
I was studying the CRUD documentation but somehow I miss the point. I want to implement in the `index()`  action different `WHERE` conditions depending on some parameters I obtain from the URL.

Reading https://crud.readthedocs.io/en/latest/events.html doesn't really help me. I tried this very simple code in the `index()` function:

    public function index()
    {
        $this->Crud->on('beforeFilter', function(\Cake\Event\EventInterface $event) {
            $event->getSubject()->query->where([ "partner_type" => "AGENT" ]);
        });

        return $this->Crud->execute();
    }

This means, **each call** of the `index` action should add the `WHERE` condition `partner_type = 'AGENT'` and return only those rows but all rows are returned.

What do I misunderstand?

**Comment by raul338** [comment]
You have to modify the query on the [beforePaginate](https://crud.readthedocs.io/en/latest/events.html#crud-beforepaginate) event.

The beforeFilter is triggered before crud decides to use the index action.

**Comment by VARGA-Peter** [comment]
Thank you very much! I did **NOT** try this one. Shame on me!
