### ISSUE TITLE
Document useModel() Method.

### ISSUE THREAD

**Issue by TerryKern** [FriendsOfCake/crud#679]
I am using:

CakePHP version: 3.10.4
Crud version 5.5.1

I was attempting to use the CRUD plugin on a table from within in a plugin. I had to manually search the code until I found the `useModel()` method. I knew that I had to specify that my table was in a plugin, however, since this method wasn't mentioned I spent quite some time searching for it. Would be nice to mention `useModel()` in the docs.

**Comment by asgraf** [comment]
I had encountered similiar problem.
My workaround was putting following code inside your AppController::beforeFilter():
```PHP
        $action = $this->Crud->action();
        $modelType = $this->getModelType();
        if ($modelType !== 'Table') {
            $action->setConfig('modelFactory', $modelType);
            //line below is required only if you also want use CrudView
            $this->Crud->listener('view')->setConfig('modelFactory', $modelType);
        }
```
