### ISSUE TITLE
Errors when visiting `/error` url

### ISSUE THREAD

**Issue by asgraf** [FriendsOfCake/crud#681]
Steps to reproduce:
1) Create new cakephp application from [cakephp/app](https://github.com/cakephp/app)
2) [Install Crud plugin](https://crud.readthedocs.io/en/latest/installation.html)
3) Visit https://localhost/error (I assume you are working on a localhost domain)

You will get following errors:
```
notice: Undefined property: ErrorController::$Crud in /application/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php on line 97
```
```
error: [TypeError] method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /application/vendor/friendsofcake/crud/src/Controller/ControllerTrait.php on line 97
```

**Comment by ADmad** [comment]
Either add a `parent::initialize()` call to your `ErrorController::initialize()` or include the `ControllerTrait` for the individual controllers instead of `AppController`.

**Comment by ADmad** [comment]
Add `$this->dispatchComponents['Crud'] = false` in your `ErrorController::initialize()`.

**Comment by asgraf** [comment]
It worked. I suggest adding this to installation manual.
