### ISSUE TITLE
Question: why does Crud component throw an exception when there's a response?

### ISSUE THREAD

**Issue by geoidesic** [FriendsOfCake/crud#682]
https://github.com/FriendsOfCake/crud/blob/master/src/Controller/Component/CrudComponent.php#L553

It feels to me like the exception system is being used as a render mechanism here instead of for errors... or am I missing something?

**Comment by davidyell** [comment]
I think something like this is okay, as it gives options to the developer on how they handle that exception. Mostly because if the event did return a response, by using an exception the calling code can catch it and still choose to return the response.

**Comment by geoidesic** [comment]
Ok tx.
