### ISSUE TITLE
Setting add and edit associations deeper than one level with relatedModels

### ISSUE THREAD

**Issue by PrincipalFirebush** [FriendsOfCake/crud#692]
Hi,
Some time ago I needed to save a record via CRUD that had associated models deeper than one level.
Fx.
`$this->Crud->listener('relatedModels')->relatedModels(['Files.FileTypes.FileExtensions'], 'add');`

But it doesn't allow that. I had to add this instead in to each "add" and "edit" method:
`
$this->Crud->action()->saveOptions([
    'associated' => ['Files.FileTypes.FileExtensions']
]);

Is that intentional? Or can it be fixed? Or is there a proper way to it?
`

**Comment by ADmad** [comment]
RelatedModels listener only handles fetching of related models, not saving.

`Table::save()` only saves associated records 1 level deep by default, so having to use `saveOptions()` each time for saving deeper association is expected.
