### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by frankvanhest** [FriendsOfCake/crud#697]
Hi,

Is it possible to bring out a new release?
Thank you in advance.

Cheers,

Frank

**Comment by ADmad** [comment]
What problem do you have with the current release(s)?

**Comment by frankvanhest** [comment]
On a project I'm depended on https://github.com/FriendsOfCake/crud/pull/691, which is not yet released. I would like to remove the dev-master from my composer.json. 
A new release would solve this for me.

**Comment by ADmad** [comment]
Done
