### ISSUE TITLE
Crud ExceptionHandler

### ISSUE THREAD

**Issue by chrisShick** [FriendsOfCake/crud#704]
I started playing around with the Crud plugin using Cakephp 5.x. I set up a basic Post controller. 

It appears the Exception handler isn't formatting the errors in json or xml. It can be tested by going to /posts/1fdlakjf and it outputs everything in the standard html. 

I did the same test using Cakephp 4.x and it works perfectly fine.

**Comment by ADmad** [comment]
Crud doesn't have a ExceptionHandler, it has a ExceptionRenderer.

Anyway, the way automatic switching of view class based on the request is handled has changed in CakePHP 5.x. So make your `ErrorController` is updated for proper [content type negotiation](https://book.cakephp.org/5/en/controllers.html#content-type-negotiation).

**Comment by chrisShick** [comment]
Apologies @ADmad !! It was a bit late last night/early this morning when I submitted this. I mistyped and meant the ExceptionRenderer. 

Thanks for the information. This would be a great addition to the crud documentation.
