### ISSUE TITLE
One catch-all controller for all tables instead of a separate controller for every table?

### ISSUE THREAD

**Issue by mehov** [FriendsOfCake/crud#708]
Hi everyone

I have about 20 tables that I want to use with the CRUD plugin.

[Using It In Your Controllers](https://crud-view.readthedocs.io/en/latest/quick-start.html#using-it-in-your-controllers) says:

> Any controller inheriting from AppController will automatically implement the specified actions loaded int the CRUD component configuration. Therefore, you can just leave your controller code empty!
>
> ```
> <?php
> namespace App\Controller;
> 
> class CategoriesController extends AppController
> {
>     // No code here, but we have all actions available to use!
> }
> ```

So if I have 20 tables, I'm looking at creating 20 controllers.

Is there a way have a catch-all of some kind?

**Comment by davidyell** [comment]
I would just bake them

https://book.cakephp.org/bake/3/en/usage.html

**Comment by mehov** [comment]
Seems to be a duplicate of my own issue from 2021: FriendsOfCake/crud-view#288

**Comment by ADmad** [comment]
The `ControllerFactory` will throw an exception if a controller class doesn't exist for the matching route before crud even comes into the picture.
