### ISSUE TITLE
How does FriendsOfCake/crud know which model to use?

### ISSUE THREAD

**Issue by mehov** [FriendsOfCake/crud#709]
If I don't specify a model using `$this->Crud->useModel()`, the plugin somehow detects the model from the URL I'm visiting. So for `example.com/crud/articles` it would rightfully guess I want the `Articles` table. How?

I looked through every line of `grep -RinF "model" vendor/friendsofcake` but I can't see the point where it would do the detection.

I found `_modelName` (https://github.com/FriendsOfCake/crud/blob/440be3b527a91816e4abe0a0a5cabc09bdffc04d/src/Controller/Component/CrudComponent.php#L81) and it looks like what could be used to hold the model name, but it doesn't seem to be used for anything other than the aforementioned explicit `useModel()`.

**Comment by davidyell** [comment]
As I recall, and I haven't looked at the code. It catches in a listener which listens for missing route paths. As CakePHP is a convention over configuration framework, the first part is assumed to be the model name, and as such a model should exist.

Learn about Cakes conventions over here https://book.cakephp.org/5/en/intro/conventions.html#cakephp-conventions

The crud documentation even mentions the listener https://crud.readthedocs.io/en/latest/installation.html#configuring-the-controller
